### ISSUE TITLE
Scroll bar doesn't stick to the bottom when window shrinks

### ISSUE THREAD

**Issue by Ralith** [mujx/nheko#100]

**Comment by mujx** [comment]
Could you provide some more context?

**Comment by Ralith** [comment]
When you resize the window to a smaller size, the timeline views scrollbar jumps upwards. It would be more useful if it stuck to the bottom.

**Comment by mujx** [comment]
I experience the exact opposite, the scroll-bar always moves (or stays) to the bottom when I resize the window.

**Comment by jansol** [comment]
Can confirm that this happens (macOS, retina) maybe 50% of the time. Maybe it's related to the problems where it doesn't stick to the bottom when new messages arrive. Could it have something to do with DPI?

**Comment by jansol** [comment]
Confirmed on Linux (NixOS) with KDE plasma on a HiDPI screen.

**Comment by Ralith** [comment]
Probably not DPI related; my system is not HiDPI.

**Comment by PureTryOut** [comment]
@Ralith could you try again? This does not seem to be happening any more for me.

**Comment by mujx** [comment]
Switching to a native scrollbar seems to have fixed this issue. Can anyone else confirm?

**Comment by mujx** [comment]
Closing as resolved. Feel free to re-open if the issue persists.
