### ISSUE TITLE
Dark system theme and incorrect UI colors

### ISSUE THREAD

**Issue by unclechu** [mujx/nheko#112]
886edd03fbc0181d3ba55a85927b0b82cf45ac93
Here is screenshots of context menu, settings screen and file manager.
![nheko-ui-issue__context-menu](https://user-images.githubusercontent.com/799353/32328351-8207fbb2-bffb-11e7-923b-338a8a1a4cb7.png)
![nheko-ui-issue__settings-screen](https://user-images.githubusercontent.com/799353/32328353-8282acae-bffb-11e7-9a3e-b3b131201248.png)
![nheko-ui-issue__file-manager](https://user-images.githubusercontent.com/799353/32328352-82472152-bffb-11e7-9d61-047dc4a43921.png)

**Comment by vurpo** [comment]
See PR #104, which will (hopefully, maybe) resolve any system theme problems

**Comment by mujx** [comment]
Fixed by 552941118bb7f94bfb3ff8c7f854380408c85ffe
