### ISSUE TITLE
Videos not displayed (no hint that there's a video at all)

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#115]
### System:
- Operating System: Arch Linux x86_64
- Qt version: 5.9.2-1
- C++ compiler: GCC 7.2.0
- Desktop Environment: i3
- nheko version: ddb23105f1b6b270f4af0653ea246b7bfef1358e

### Actual behavior
Video not displayed. There's not even a link or another indication. All people go: *woo cool video!* and I don't see anything 😉 

### Expected behavior
Displaying a link to the video would be cool.

### Steps to reproduce
Have someone send a video into a channel via Riot.

**Comment by mujx** [comment]
Basically this comes down to add support for the `m.video` message type. At least with a widget that just displays the link.

**Comment by Ralith** [comment]
[§11.2.1.1](https://matrix.org/speculator/spec/HEAD/client_server/unstable.html#m-room-message)
> The body key is text and MUST be used with every kind of msgtype as a fallback mechanism for when a client cannot render a message.

It is a bug that nheko does not display anything at all for unsupported events, including videos.

**Comment by rodneyrod** [comment]
I found the perfect image to use as a placeholder

http://blog.adriansandu.com/wp-content/uploads/2012/08/chrome-broken.png

**Comment by mujx** [comment]
The event message isn't [parsed](https://github.com/mujx/nheko/blob/master/src/TimelineView.cc#L226) at all. Adding support to just display the video/audio url is very simple.
