### ISSUE TITLE
Typing notifications are triggered by modifier keys (ctrl, alt, etc)

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#116]
Those keys should be excluded. For example, typing ctrl-k to open the room switcher will trigger a typing notification.

**Comment by karroffel** [comment]
The current way simply starts the typing notification in the `keyPressEvent` method and doesn't check if it's actually a key that will ultimately change the text inside the input field. 

https://github.com/mujx/nheko/blob/13cb0521fa4fd692f66a89c83ef17b7e3ea339bb/src/TextInputWidget.cc#L40-L45
