### ISSUE TITLE
Olm support

### ISSUE THREAD

**Issue by ZWindL** [mujx/nheko#13]
Will this client support olm?

**Comment by mujx** [comment]
Eventually yes, that's the plan at least.

**Comment by ZWindL** [comment]
wow! good, thanks.

**Comment by mujx** [comment]
It's too early to be thinking about Olm though. There are lots of basic features that need to be implemented first.

**Comment by Qualitymix** [comment]
On the contrary, I think one of the primary reasons anyone would choose to use Matrix as a service is the end to end encryption it provides.  It's the only reason I'm still forced to use the Riot client.    I would think that this feature would be far more important than animated GIFs or other features.

**Comment by MTRNord** [comment]
@Qualitymix i think it is the hardest Feature too at the same time ;) that's why it isn't added early

**Comment by mujx** [comment]
@Qualitymix Currently my focus is on providing a stable base, so you won't have to log into Riot to use Matrix. Vital features like joining a room and accepting an invite are missing. After this goal is achieved I would definitely look into encryption (and yes, encryption is more important than gifs 😛).
Of course any contributions towards that direction are really welcome.

**Comment by ReK2Fernandez** [comment]
Dude every channel I get invited uses encryption.. this is VERY Important.. is one of the top 10 usabily things.. almost no channel is open now a days.. at least not the important ones.. so please make this a priority im so tired of electron is not even funny. :P

**Comment by mujx** [comment]
@ReK2Fernandez Yeah, I guess it's time to at least start looking into e2e because the basic features are already there.

**Comment by ReK2Fernandez** [comment]
@mujx thanks for the reply, hehe I think im not the only one tired of electron and looking for a decent desktop app :) any ideas when development will start? I am so eager I wont mind alpha/beta testing

**Comment by qazip** [comment]
I'm also definitely tired of that other bloatware, so much that I wont be using matrix until there's a proper client with E2EE (This is a feature I absolutely need). 

@mujx, do you've any sort of ETA for E2EE?

**Comment by mujx** [comment]
@qazip There isn't an ETA because there hasn't been any progress yet, mainly due to the lack of time from my side.

**Comment by mujx** [comment]
Just an update on the roadmap for e2ee.

There is a new repo (https://github.com/mujx/mtxclient) for a client library for matrix, which will have all the encryption related parts & it will replace the current ad-hoc matrix client implementation on nheko. This was done so we can improve the test-ability (very important for the crypto implementation) of the library and decouple it from qt, so it could be used on non-qt applications.

The first step is implement the endpoints currently in use in nheko (1 - 2 weeks), so we can make the switch & then we can start working towards the e2ee functionality.

**Comment by albjeremias** [comment]
Please dont commit the same mistakes as the riot.im people... (btw awesome work here :))))

Here some tips:
### A How-to manual, on how-to use riot properly with security and privacy by default. We are a group that have been testing riot and we found out some issues, we make this as a disclosure.. feel welcome to participate

>  Providing an illusion of security is worse than no security at all in most cases but i respect the work done here anyways

# riot issues 
Decrypt attachments
 > - decrypt attachments on external host, even though we created our own homeserver... usercontent.riot.im 
 > - quotes from #riot:matrix.org developer: 
  >  - "is a few lines of sandbox which riot-web sends HTML into to run the potentially unsafe javascript from a domain that has no access to anything like your matrix token" 
  >  - "https://github.com/matrix-org/usercontent/blob/master/v1.html is the content of usercontent.riot.im - feel free to run your own. Render user generated content with a different origin to the main application." 
  >  - "I'd find the lack of it alarming" ... "as then you're open to XSS attacks"
  
Manage integrations
![matrix integrations](https://cloud.disroot.org/index.php/apps/files_sharing/ajax/publicpreview.php?x=1920&y=557&a=true&file=riot_integratiosn.png&t=5QewacpAQxkHnkf&scalingup=0)
> - When you go to the channel integrations, and click on the matrix whatever button... you get a dialog window with a list with many #capitalist #spying companies, like integrate a youtube video, a google doc, a google calendar, spotify?, slack, gitter, github, google search image, travis ci

verified devices and unverified devices.. what a mess?? Why by default I send messages to unverified devices? 
> - How can I revoke previous verified devices from other users? -> this is possible just click on the user and click on unverify
> - You should also activate the option "Never send encrypted messages to unverified devices from this device" on your settings
 
webrtc
> - Webrtc is a web technology which leaks your external ip, and even your LAN ip address.. | https://browserleaks.com/webrtc
> - You can disable it on the settings "Disable Peer-to-Peer for 1:1 calls", and also I'd recommend to disable it on your browser https://github.com/vector-im/riot-web/issues?q=is%3Aissue+webrtc+is%3Aopen

# matrix issues

Read Receipts
> - Read receipts are also used for remembering and syncing what messages you have read, so Riot doesn't have an option to disable them. ( https://github.com/vector-im/riot-meta/issues/66 ) it should be a matrix issue.. so its compatible with other clients
   - https://github.com/vector-im/riot-web/issues/2527
   - https://github.com/vector-im/riot-android/issues/1151
      You can disable them on your own instance: https://github.com/vector-im/riot-web/issues/2527#issuecomment-285822388

**Comment by MTRNord** [comment]
@albjeremias out of intrest: is there some actual Suggestion about the Integration or is your comments pure "flaming"? The reason of having Integrations is exactly to have third-Party Software in riot. (and if you just dont like it because scalar is closed source: there is also Dimension by TravisR

**Comment by albjeremias** [comment]
Hi sorry.. I didn't meant to be rude... i am just concerned user with my privacy, security and be free as in freedom from companies which make profit from my data. It's very sad to see the comment deleted and I'm sorry if it sounded like flame, i would like people to join on making great software for privacy and security, in the style of tails.. it could also be optional of course..

**Comment by MTRNord** [comment]
@albjeremias about the Integrations: none of them get any Information about you until you activate them manualy. But that's not a discussion for this issue

**Comment by mujx** [comment]
@albjeremias I deleted the comment because most of its contents were not meant for this issue or project, but for Riot's issue tracker, so in this context it looked like spam/rant (e.g nheko doesn't use javascript, so there is no point discussing XSS). 

The only relevant comments were about the read receipts for which there is an issue already (#261) & the UI/UX of the unverified devices for which you can open a separate issue.

This issue is used primarily to track the status of e2ee in nheko. So far we don't have anything implemented. Please don't take this the wrong way, you're of course very much welcome to help nheko & matrix in general but please try to keep things on topic.

**Comment by mujx** [comment]
An not so extensive checklist towards e2ee https://github.com/mujx/mtxclient/issues/24

**Comment by qazip** [comment]
Am I reading this right? Does nheko support E2EE now?

**Comment by mujx** [comment]
@qazip Yes the core is there. There are some things left to be implemented and make it more robust.

**Comment by lbeltrame** [comment]
Would bug reports be already welcome, or is it too soon? (As I just built this from source and played a bit with it) - Also I assume reports (if wanted) should go to mtxclient rather than nheko?

**Comment by mujx** [comment]
@lbeltrame Reports are most certainly welcome. If you're using nheko open an issue here.
