### ISSUE TITLE
plans for release version tagging?

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#133]
From reading the nheko channel, it seems like some people are already tagging nheko for various Linux distributions (and we're also doing it for postmarketOS as you know).

Additionally, I guess by now at least a hand full of people use nheko as daily driver. So what do you think about tagging `0.x` releases every now and then, to make packaging easier?

(I've also asked for [lmdb++](https://github.com/bendiken/lmdbxx/issues/21).)

**Comment by jansol** [comment]
That is the plan (as has been discussed in said channel a bit before the postmarketOS stuff). For now there's only [https://github.com/mujx/nheko/releases](nightly) tag, but once the critical features are implemented @mujx intends to start tagging numbered versions too.

**Comment by mujx** [comment]
I will start version tagging when the `0.1.0` milestone is completed. I won't add any more features to it except the PRs for theming and communities.

**Comment by shirishag75** [comment]
there is https://github.com/mujx/nheko/blob/master/CHANGELOG.md which does tell what nheko version was released with what changes so that's good.
