### ISSUE TITLE
Segmentation Fault on Arch Linux

### ISSUE THREAD

**Issue by vanyasem** [mujx/nheko#136]
Both AUR and AppImage versions of Nheko segfault on Arch Linux

### System:

- Nheko commit/version: 4166a86 (AppImage) / AUR
- Operating System: Arch Linux 64-bit
- Kernel 4.13.12-1-ARCH
- Qt version: 5.9.2
- Desktop Environment: KDE Plasma 5.11.3 (KDE Frameworks 5.40.0)

### Expected behavior
nheko is able to login successfully

### Actual behavior
nheko segfaults shortly after showing spinner splashscreen

### Steps to reproduce
1. Launch nheko
2. Login to your matrix.org account
3. Watch the spinner and wait for it to crash

### Debugger traceback 
`strace` output
[strace.log](https://github.com/mujx/nheko/files/1485992/strace.log)

**Comment by vberger** [comment]
To you have an HiDPI display? If yes, it could be that you go struck by this Qt bug : https://bugreports.qt.io/browse/QTBUG-64239

**Comment by vanyasem** [comment]
Yes I do. 4K monitor set up with x2 scaling. Other non-HiDPI monitors are downscaled with xrandr

**Comment by mujx** [comment]
`qt5-base v5.9.3` is now available on Arch. Could you check if it solves the issue?

**Comment by vanyasem** [comment]
It doesn't segfault, but still crashes shortly after login. I believe that's a separate issue though

**Comment by mujx** [comment]
The AppImage version crashes because it's built on Travis with qt5.9.2 which still has the bug mentioned above.
