### ISSUE TITLE
White font in fields and «&» in buttons.

### ISSUE THREAD

**Issue by commagray** [mujx/nheko#14]
Subj, pic related.
![screenshot_20170502_012950](https://cloud.githubusercontent.com/assets/27947961/25597368/f7ab549c-2ed6-11e7-8804-c4e589af4dc0.png)
![screenshot_20170502_013100](https://cloud.githubusercontent.com/assets/27947961/25597375/04fa02d8-2ed7-11e7-8a76-0acb5b568add.png)
Or it's a feature? :3

**Comment by mujx** [comment]
Those are bugs unfortunately. Could you provide some more info about your system?

- OS
- Qt version

**Comment by commagray** [comment]
OS: Arch Linux with enabled all [*-testing] and [kde-unstable] repository.
Qt: 5.9.0beta2

**Comment by mujx** [comment]
Being on unstable is what might have caused those bugs. I'm on Arch too but I haven't tested nheko on 5.9 yet, so technically it's not supported, but I will give it a shot in the next couple of days. Could you test it in a more stable environment?

**Comment by commagray** [comment]
Btw, new problem — I can't login. More precisely, I have logged on, but after restart I see again main menu and after clicking on «Login» button comes infinite loading bar, and output in terminal: "Host requires authentication". Can you tell where is config or what file placed for delete them?

Okay, I'll downgrade and test.

**Comment by mujx** [comment]
The config is in `~/.config/Nheko`. Looking at your screenshot you might have used the register page which doesn't work yet.

**Comment by mujx** [comment]
Ignore the last sentence , I misread your comment. If the problems continue join the chat room on Matrix.

**Comment by commagray** [comment]
I downgraded and rebuilded client with Qt 5.8 from «extra» repository and actually nothing changed — I still have «&» in buttons. Font issue is «solved» by changing KDE theme to bright variant of Breeze, but I think this is not a solution.

**Comment by mujx** [comment]
Turns out KDE is the problematic component. I was able to reproduce  the "&" bug with Plasma. I will investigate some more.

**Comment by PureTryOut** [comment]
I can reproduce it as well on my laptop. Interestingly enough it doesn't happen on my desktop.

**Comment by mujx** [comment]
@PureTryOut Anything different between laptop and desktop? (Desktop Environment, OS etc)

**Comment by PureTryOut** [comment]
Not that I know. Both run Gentoo Linux with about the same configuration, and both run XFCE.

**Comment by Ancurio** [comment]
Happens for me as well, xfce4 4.12 with "dusk" GTK3 theme. The thing with dark themes is that they usually render text in white, so since you've forced a white background on your login screen, you would have to force a black text color too.

**Comment by mujx** [comment]
9de94061ec71cd023cc538d00b76e9097e12f0c9 problably fixes the white font issue.

**Comment by Ancurio** [comment]
> 9de9406 problably fixes the white font issue.

I'm gonna have to check, but I tried your `setTextColor()` before and it had no effect.

**Comment by commagray** [comment]
> 9de9406
Nope.

**Comment by mujx** [comment]
Does the patch from @Ancurio fixes it?

**Comment by commagray** [comment]
Yup, it totally does.

**Comment by z3ntu** [comment]
Same problem on Arch

qt5-base 5.8.0-11
plasma-desktop 5.9.5-1

Also Breeze Dark theme.

**Comment by mujx** [comment]
The problem seems to be that KDE automatically adds accelerator mnemonics. 

Related [issue](https://bugs.kde.org/show_bug.cgi?id=337491) and possible [solution](http://stackoverflow.com/questions/32688153/how-to-disable-automatic-mnemonics-in-a-qt-application-on-kde).

**Comment by z3ntu** [comment]
Potentially something like this is possible: https://github.com/fkie/multimaster_fkie/commit/8801b5b8cde0099ca358c9d8b54679ce656388d8
