### ISSUE TITLE
Messages don't get sent (without any indication that sending failed)

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#142]
### System:

- Nheko commit/version: b21942a3e3db3e425155c58483a99bc2789de241
- Operating System: Arch Linux
- Qt version: 5.9.3-1
- C++ compiler: gcc=7.2.0-3
- Desktop Environment: i3wm

### Actual behavior
Sending messages *appear* to be working, but in reality they don't get sent. I notice it later when other people answer stuff I have already answered for example. Then I open riot in the browser and it shows that at some point `nheko` stopped sending my messages.

Restarting `nheko` temporarily resolves this, but it happens again very fast.
This happened for the fist time a few days ago (I always build the latest version before running nheko). Since then I've been careful not to send too many messages without waiting between them, but it still happens.

An indication, that the latest message was not sent is, that on the left where it shows the last message in a channel, it doesn't display my message. But that isn't always reliable, I've had the case at least once when it *did* show my message there, but it was not sent.

I am using TOR if that matters (network connetion is worse than without it).

### Expected behavior
Send the messages or at least show that the messages were not sent (and offer to retry?).

### Steps to reproduce
Try to send messages as usually, maybe with using `tor`.

Please let me know if I can help with resolving this, unfortunately it makes `nheko` almost unusable for me.

**Comment by Ralith** [comment]
I (and based on discussion in the matrix room, others) have observed this as well. Seems to be a bug causing the unsent messages queue to get stuck.

**Comment by mujx** [comment]
@ollieparanoid Could you try spamming messages quickly in a room using nheko and see if the messages stop coming after a while? Just to verify if it's the message queue bug which I'm also experiencing but only through the spamming method mentioned above.

**Comment by ollieparanoid** [comment]
I've just tested it. 8 messages prepared to be sent to a channel, copy pasted them one after another and only the first one got through (as verified with Riot).

**Comment by ollieparanoid** [comment]
Actually the messages are displayed twice in nheko now. First the 8 ones sent from nheko, from which only the first one got sent for real, then the 7 ones I've written with Riot.

**Comment by mujx** [comment]
@ollieparanoid A fix is in place now. Please let me know when you have the chance if the issue has been resolved.

**Comment by ollieparanoid** [comment]
Awesome! I'll try to test it tomorrow.

**Comment by ollieparanoid** [comment]
**And it worked \o/** Thank you so much for fixing this! 🎉 🎉
