### ISSUE TITLE
[AppImage] nheko crashes on startup

### ISSUE THREAD

**Issue by simoniz0r** [mujx/nheko#144]
### System: 

- Nheko commit/version: b9c4a819ade7798c0c464151cc086bae911a1654
- Operating System: OpenSUSE Tumbleweed and Ubuntu 18.04 daily
- Qt version: 5.9.2
- C++ compiler: N/A
- Desktop Environment: LXQt

### Actual behavior
nheko crashes on startup with the error message below.  This seems like it could be a problem with the config file.  I tried removing nheko's config file, and nheko will start, but just sits at the loading screen forever.  A slightly different error is outputted when this happens.

### Expected behavior
No crash on start

### Steps to reproduce
Download the latest AppImage as of commit b9c4a819ade7798c0c464151cc086bae911a1654 and attempt to run it.

### Debugger traceback 
Error when previously used config file is left in place:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  parse error - unexpected 'q'
[1]    23554 abort (core dumped)  nheko
```
Error outputted while loading screen is shown after removing config file and logging in again:
```
35.654: [warning] - Malformed JSON response parse error - unexpected 'q'
```

**Comment by mujx** [comment]
The format of the cached data changed, so you'll have to clear the cache first.

**Comment by ollieparanoid** [comment]
In case anyone is wondering like me where the cache is:
```shell
rm -r ~/.cache/nheko
```
