### ISSUE TITLE
Please clarify build instructions

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#146]
Hi,

The readme says:
```
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release # Default is Debug.
make -C build
```
But the Makefile has:
```
debug:
	@cmake -H. -GNinja -Bbuild -DCMAKE_BUILD_TYPE=Debug
	@cmake --build build

release-debug:
	@cmake -H. -GNinja -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo
	@cmake --build build
```
Among other options.

Could these be consolidated and clarified?  It would nice to just run `make` and get the standard build.  As it is, I don't know which of these three methods is preferred, and having to run the commands manually isn't as nice as just running `make` or `make release`.

Thanks.

**Comment by PureTryOut** [comment]
I just do the following.

```
$ mkdir build && cd build
$ cmake ..
$ make
```

I'm not entirely sure why debug was made the default. It does make sense to me, but almost no other program does it.

**Comment by alphapapa** [comment]
> The Makefile you're referring to, isn't meant to be the official way to build the app. I only use it during development for some common operations so it might change from time to time.

Why don't we add a build target to the Makefile to make a standard build?  That way we wouldn't have to run several commands to do so.

**Comment by alphapapa** [comment]
Thanks!
