### ISSUE TITLE
Latest message not consistently displayed below room name

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#155]
Thanks for fixing the bug with topic messages.  I rebuilt nheko, deleted the cache, and started it.  It seems to be working mostly correctly, but only the first chat room in the list shows the latest message below it:

![example](https://user-images.githubusercontent.com/601365/33735723-c09eb440-db55-11e7-9a18-85796fd2d347.png)

However, then I restarted nheko.  On initial load, the window looked the same, with only the first room showing the latest message.  But now, when I click on a room, the room window is initially blank, then after a moment the messages are loaded, and then the latest message is displayed below the room name.  This only happens when I actually view the room.

Then I ran nheko for a third time, and its behavior is the same as the second time.

Thanks.

**Comment by mujx** [comment]
This is the expected behavior. The application initially will only load the sent messages after your last sync.

**Comment by alphapapa** [comment]
Sorry, I don't understand.  Before the `matrix-structs` changes, it didn't work this way.  Whenever I launched nheko, all the rooms would display their latest message.

Also, as far as I have seen, when `/sync` is called without `since`, every `join` room will list the last few messages.  So nheko should receive messages for every room on first sync, and it shouldn't be necessary to click the room to load the latest messages when nheko is started.

Are you caching the `since` token and reusing it after closing and restarting the program?  I can see why you might do that, but I'm not sure it is the most useful behavior.  When I start nheko, I want to see the latest messages in the room list so I know if there are new ones, or if the last one is one I've already seen, without having to click each room.

Thanks.

**Comment by mujx** [comment]
> Sorry, I don't understand. Before the matrix-structs changes, it didn't work this way.

It did. It works like this from this commit (f1eb0bbac0fab61f0d497a60ec6640c97cbe5668).

> Are you caching the since token and reusing it after closing and restarting the program?

Not only the token but the whole state until the last sync you made. 

> When I start nheko, I want to see the latest messages in the room list so I know if there are new ones, or if the last one is one I've already seen, without having to click each room.

That's what happens. If you don't see antyhing below a room name it means that there were **no** new messages **since** your last sync.
