### ISSUE TITLE
Configurable font size

### ISSUE THREAD

**Issue by pztrn** [mujx/nheko#161]
Please add a configuration setting for changing font size. It is too small for me. I'm on Debian 9 with Qt5 5.7.1.

![default](https://user-images.githubusercontent.com/869402/33982203-8224e8fc-e0d1-11e7-9cfc-e1cc355d74d7.png)

**Comment by mujx** [comment]
There should be a base font size from which all the other sizes will be computed (implementation note).

**Comment by alphapapa** [comment]
I would appreciate this.  The change in https://github.com/mujx/nheko/commit/94b2827051982329c53e64e7f7e5e7270442bac9 has made the font sizes much too large on my system.

**Comment by ChrisDeChef** [comment]
+1

**Comment by thinslice** [comment]
How about implementing it as a multiplier on top of the Qt font size? (or an option to choose either manual font size or Qt font size)

This way you could customize it, and people who alter the Qt font size would get a better font size out of the box.

**Comment by dessalines** [comment]
Font size and the QT Auto scaling are the main things preventing nheko from being my main matrix client.

**Comment by spantaleev** [comment]
Seems like the **Scale factor** setting works well as an alternative to setting a font size.

**Comment by digver** [comment]
Scale factor makes it usable for me, but on its own not too pretty
