### ISSUE TITLE
Build fails: Could not find a package configuration file provided by "Qt5LinguistTools"

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#162]
I tried to build today with recent changes, but it fails because of a new requirement:
```
CMake Error at CMakeLists.txt:57 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/me/tmp/src/nheko/build/CMakeFiles/CMakeOutput.log".
make: *** [release] Error 1
```
I have the PPA configured for Qt 5.9 on Ubuntu Trusty, but I can't find any package to install for Qt5LinguistTools.  I updated all submodules.

Thanks.

**Comment by mujx** [comment]
This isn't a new requirement. Did you install `qt59tools`? You will also need to add `/opt/qt59/bin` to your path. You can take a look at the Dockerfile to see exactly how to create a dev env for nheko.

**Comment by alphapapa** [comment]
Argh, I'm sorry, I was trying to use the new `make release`  target, but I forgot that that doesn't have the right paths in it.  My bad!
