### ISSUE TITLE
Request: Allow window to be made smaller

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#163]
Hi again,

I just discovered that the room list can be shrunk to the icons.  This is really nice, as I don't need the room list taking up a lot of space all the time!  

But now I'm left with a really big message list in the current room.  For some reason, I can't make it smaller than about 796 pixels wide.  In my main room, which is just me and a friend, the message list is about 85% whitespace, so I'd like to make it narrower to take up less screen space.

Would it be possible to remove these hard limits and let the window be made smaller?

Thanks!

**Comment by mujx** [comment]
Is it related to #160?

**Comment by alphapapa** [comment]
I don't think so.  I removed that from the config file and restarted.  I still can't make the window any smaller.

**Comment by alphapapa** [comment]
I just built and ran the latest commit.  I can't make the window any narrower than this:

![nheko](https://user-images.githubusercontent.com/601365/34116315-d8b1652e-e3dd-11e7-8f77-9620a4484078.png)

Thanks.
