### ISSUE TITLE
Docs: Please note large size of git submodule repos

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#164]
Hi,

Small issue here, I noticed that the `matrix-structs` submodule is over 200 MB in size, which includes very large JSON files uses in tests.  I only noticed this because I saw my local backup set increase by hundreds of megs unexpectedly, and I tracked it down to these files.  As a result, I moved my copy of the repo to a directory which isn't in my backup set, but now I have to delete that backup generation to recover the disk space (it's a little backup server which is gradually running out of space).

So please consider adding a note to the readme about the size of the submodule repos, suggesting that users may want to put the `nheko` repo in a directory where it won't get backed up.

Thanks for your great work on `nheko`, it's exciting to see it constantly improving!

**Comment by mujx** [comment]
Good point. I will remove the submodules entirely actually, cause I only need a header file for each dependency.
