### ISSUE TITLE
"make clean" will delete user data in working tree

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#167]
Hi,

In https://github.com/mujx/nheko/commit/7e24a468b5762a1f40710eb4b4a7b522659567c7, the `make clean` rule was changed.  Please don't use `git-clean -xdf` here.  That should only be run by users manually.  I understand how convenient it is, but this will wipe out files in the repo that git isn't tracking and cause data loss.

For example, after all the times I forgot to run the build process correctly, I finally made a script to do it, and put it in the repo directory.  I can't have git track it without causing conflicts, of course, so I haven't used `git add` on it.  Instead I added it to `.git/info/exclude` so git will think the repo is clean.

But `git clean -xdf` ignores that:

> Don’t use the standard ignore rules read from .gitignore (per directory) and $GIT_DIR/info/exclude

That means that running `make clean` will delete my build script, and I'll have no way to recover it since it isn't tracked in the repo.  And since I run `make clean` in the script, the next time I run it, it will delete itself.  :(

**Comment by mujx** [comment]
Reverted the change back to `rm -rf build`.

**Comment by alphapapa** [comment]
Thanks.
