### ISSUE TITLE
Loading the backlog is broken for deleted messages

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#168]
### System:

- Nheko commit/version: 101bf47443a1005f09e5369f232719cd9b67c189
- Operating System: Arch Linux
- Qt version: 5.10.0
- C++ compiler: 7.2.1
- Desktop Environment: i3wm

### Actual behavior
There was an IRC spambot in the channel, and it left lots of spam messages. Another user in the channel removed all of them (they show up as lots of single deleted lines in Riot).
When scrolling up to see the backlog in `nheko` it loads fine until the last message is "ok all spam messages removed... pfft what a work".

### Expected behavior
Scrolling up works even with removed messages.

### Steps to reproduce
I guess creating one or more deleted messages (messages can be deleted in Riot) followed by lots of normal messages, then open nheko and try to scroll up above the deleted message.

**Comment by mujx** [comment]
I am not sure I understand the problem here. Did you expect to see the deleted messages or the issue is that the scrollbar doesn't move any further.

**Comment by alphapapa** [comment]
@mujx I think nheko isn't handling redaction events.  I saw some JSON dumps in the console today from a room I was in, saying "Invalid event type".

**Comment by PureTryOut** [comment]
@mujx the problem is that the scrollbar doesn't move further. I was the one deleting the messages @ollieparanoid mentioned, and I already noticed it didn't scroll up further (immediately after deleting the message, no other messages after the deletion are necessary).

**Comment by mujx** [comment]
@PureTryOut @ollieparanoid Are you able to reproduce the issue in another room?

**Comment by PureTryOut** [comment]
I just created a test room, and it seems I can not, which is interesting. Obviously nheko didn't remove the message on the timeline, but after a restart the deleted message was gone and the message before it was loaded fine. What *is* weird though is that some messages appear as a new user.


![screenshot_2017-12-23_14-35-08](https://user-images.githubusercontent.com/1565836/34319941-8d823cc6-e7ee-11e7-962f-a1fc4d5ec804.png)

However, that has nothing to do with this issue.

**Comment by mujx** [comment]
The user avatar appears again because each message chunk is rendered independently of the previous messages.

**Comment by mujx** [comment]
Not sure if this is relevant https://github.com/vector-im/riot-web/issues/5845. Maybe we can reproduce the error after deleting a lot of messages.

**Comment by mujx** [comment]
I was able to reproduce this error in a room that had a lot of messages deleted (`#ruma:matrix.org`). 

The `/messages` endpoint can sometimes return 0 events even though the next call would return a non zero number of events. Nheko interprets 0 events as if the timeline is over for that room and it stops fetching more messages.

**Comment by mujx** [comment]
The bug is nheko. If a batch only contains `m.room.redaction` events there are not parsed. I will update the parsing to include those events.

**Comment by ollieparanoid** [comment]
Unfortunately that bug appeared again today. There are quite some pages of backlog which I scroll through, and then I can't scroll up further anymore. Checking in the Riot web interface, a deleted message is exactly at that location.

### System
- Nheko commit/version: b78f101 Add Dockerfile to create an AppImage for Debian
- Operating System: Arch Linux x86_64
- Qt version: 5.10.0-3
- C++ compiler: GCC 7.2.1+20180116-1
- Desktop Environment: i3wm
