### ISSUE TITLE
Handle redactions

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#171]
- [x] The user should be able to redact messages if he has enough power.
- [x] Redacted messages should be removed from the timeline.
- [x] Redacted messages from other users should be removed from the timeline.

**Comment by PureTryOut** [comment]
Instead of just removing it from the timeline, maybe give an indicator of the message being removed like Riot does? Or at least a setting for it.

**Comment by ollieparanoid** [comment]
If there's an indication of removed messages, it would be nice if they were grouped. In Riot there's always one line per removed message - when removing lots of spam, one line saying "50 deleted messages by user xyz" instead of 50 separate lines would make it a lot easier to scroll over it.

**Comment by christarazi** [comment]
I found an issue regarding redactions. If you redact an old message, the date is not removed. See image below:

![screenshot_2018-03-18_12-18-58](https://user-images.githubusercontent.com/3885308/37569987-486d387e-2aa7-11e8-9029-5d83be3d5678.png)

**Comment by mujx** [comment]
@christarazi I'm aware of that issue. There should be a check to remove the date separator also. PRs welcome.

**Comment by christarazi** [comment]
You can assign this one to me.

**Comment by mujx** [comment]
@christarazi I opened an issue for it #276

**Comment by PureTryOut** [comment]
So, from what I understand the messages are just removed now? Can we get that option to still show it's deleted like Riot does?

**Comment by mujx** [comment]
I opened a separate issue for this #277
