### ISSUE TITLE
Room list does not have a scrollbar

### ISSUE THREAD

**Issue by pafcu** [mujx/nheko#174]
### System:

- Nheko commit/version:f11044b5eb9cf42cc71930b567b7566f1293a936
- Operating System: openSUSE Tumbleweed
- Qt version:5.9.3
- C++ compiler: gcc 7.2.1
- Desktop Environment: KDE

### Actual behavior

Room list does nor have a scroll bar. The only way to scroll seems to be using the mouse wheel (if you have one).

### Expected behavior

I expect there to be a scroll bar. If it is not visible all the time, at least on hover, or at the very least clicking on where it _should_ be to make it appear (like in the messages section)

**Comment by mujx** [comment]
Unlike the timeline, this scrollbar should be painted *above* the content and not on the side, otherwise it will look kinda ugly. Unfortunately Qt doesn't provide an easy way to do this.
