### ISSUE TITLE
Load last content from all rooms on initial start

### ISSUE THREAD

**Issue by pafcu** [mujx/nheko#175]
### System:

- Nheko commit/version:f11044b5eb9cf42cc71930b567b7566f1293a936
- Operating System: openSUSE Tumbleweed
- Qt version:5.9.3
- C++ compiler: gcc 7.2.1
- Desktop Environment: KDE

### Actual behavior

I have a lot of rooms in my list that is missing the last thing that was said in the room. The information is only shown once I have visited the room once

![image](https://user-images.githubusercontent.com/62835/34227664-38dccf8c-e5ce-11e7-882b-46e9c51906fc.png)

### Expected behavior

I expect the last thing to have been said in the room to always be visible, without having to separately visit the room

### Steps to reproduce

Launch nheko for the first time. Notice that the room list is populated, but the list does not show the last message in the room.

**Comment by mujx** [comment]
Check this issue #155. The reason we don't load all the messages is because it's really taxing on the homeserver (especially small instances). Maybe this could an option for those who don't mind.

**Comment by pafcu** [comment]
It could simply be rate-limited? I find it hard to believe that fetching the last message for 10 rooms would be super-demanding

**Comment by mujx** [comment]
Yup, usually the requests get rate-limited.

**Comment by pafcu** [comment]
In that case I'm confused why it needs to be an option? If it is rate-limited, it should not be really taxing on the homeserver, so it should be possible to do by default

**Comment by mujx** [comment]
I guess it should be possible when rate-limited requests are handled properly.
