### ISSUE TITLE
Emoji is inserted, but not actually shown

### ISSUE THREAD

**Issue by pafcu** [mujx/nheko#177]
### System:

- Nheko commit/version:f11044b5eb9cf42cc71930b567b7566f1293a936
- Operating System: openSUSE Tumbleweed
- Qt version:5.9.3
- C++ compiler: gcc 7.2.1
- Desktop Environment: KDE

### Actual behavior

Using the emoji picker an emoji is actually inserted in the text entry field, but is not visible (confirm by copy-pasting the text to another program where the emoji can be seen)

### Expected behavior

I expect to be able to see the emoji

### Steps to reproduce

1. Insert emoji using emoji selector
2. Notice no emoji is actually seen
3. Select text in text field, paste into other program
4. Notice that emoji is seen in other program

**Comment by mujx** [comment]
This is a Qt bug. Check this issue also #140.
