### ISSUE TITLE
Chat bubble icon does not seem to do anything

### ISSUE THREAD

**Issue by pafcu** [mujx/nheko#178]
### System:

- Nheko commit/version:f11044b5eb9cf42cc71930b567b7566f1293a936
- Operating System: openSUSE Tumbleweed
- Qt version:5.9.3
- C++ compiler: gcc 7.2.1
- Desktop Environment: KDE

### Actual behavior

Clicking on chat bubble icon (middle button at the bottom of the room list) does not actually seem to do anything

![image](https://user-images.githubusercontent.com/62835/34228840-722dd232-e5d2-11e7-947a-f79792d2b160.png)

### Expected behavior

I expect the button to do _something_

**Comment by mujx** [comment]
That's a placeholder for now.

**Comment by pafcu** [comment]
Maybe at least make the button look disabled?
