### ISSUE TITLE
Segmentation Fault on Arch Linux

### ISSUE THREAD

**Issue by robozman** [mujx/nheko#181]
### System:

- Nheko commit/version: https://github.com/mujx/nheko/commit/6835a97b15f642829ffe168464aeb1eae8f7b6a9 (Via nheko-git on the AUR)
- Operating System: Arch Linux
- Qt version: qt5-base 5.10.0-1
- C++ compiler: GCC
- Desktop Environment:  i3

### Actual behavior
nheko segfaults if no chat is currently available when either
- Clicking the three dot menu icon in the upper right
- Sending a message
![segfault_on_no_avail_chats](https://user-images.githubusercontent.com/4441464/34329376-7a2a48fc-e8cb-11e7-8906-761138e76909.png)

### Expected behavior
Nheko doesn't segfault.  Graceful error about not having a chat selected potentially
### Steps to reproduce
1. Install nheko-git from AUR on Arch Linux
2. Run nheko
3. Login sucessfully
4. Have no available chats
5. Click menu icon or send message

### Debugger traceback 
[strace.log](https://github.com/mujx/nheko/files/1585082/strace.log)

**Comment by aladar42** [comment]
Not sure if this needs verifying, but +1, same problem. XFCE/Qt 5.10.0-3.
