### ISSUE TITLE
Links aren't legible in UI dark theme

### ISSUE THREAD

**Issue by vinimlo** [mujx/nheko#183]
### System:

- Nheko commit/version: 0.1.0.r347.e1a4458a-1
- Operating System: Arch Linux
- Qt version: qt5-base 5.10.0-1
- C++ compiler: GCC
- Desktop Environment: bspwm

### Actual behavior
Links are in a dark color, just like the theme

### Expected behavior
Links clearer

### Steps to reproduce
Just send a link on a chat room, with the dark theme applied

### Image 
![issuenheko](https://user-images.githubusercontent.com/24274916/34397096-973c5466-eb51-11e7-8d60-4450706706ac.png)

**Comment by mujx** [comment]
This is a bug currently. You'll have to restart the app for the links to be updated.

**Comment by ishitatsuyuki** [comment]
First of all, why are links black?

**Comment by mujx** [comment]
@ishitatsuyuki They are not black on the dark theme. If you're switching from Light to Dark the links won't change, so you'll need to restart.

**Comment by mujx** [comment]
The colors have been updated and they are now legible on all themes.
