### ISSUE TITLE
nheko doesn't allow the window manager to resize it to custom widths and heights

### ISSUE THREAD

**Issue by PureTryOut** [mujx/nheko#187]
### System:

- Nheko commit/version: 5e0fbe87a0f2c40c4e1fdecbd52bc46d7b917931
- Operating System: Gentoo Linux
- Qt version: 5.7.1
- C++ compiler: GCC6.4
- Desktop Environment: Xfce with the Xfwm window manager

### Actual behavior

Dragging a window to the left or right side of the screen (or using the "Tile window to the {left, right}" option of Xfwm), the window just moves and nothing resizes.

### Expected behavior

The window to resize to half the size of the screen (by the window manager).

### Steps to reproduce

Set a hotkey for the "Tile window to the {left, right}" option in Xfwm, use it when having nheko focussed. Notice it won't resize (or move).

**Comment by mujx** [comment]
Possibly related to #160 or #163?

**Comment by PureTryOut** [comment]
Possibly? The width it should be resized too is bigger than the minimum width of the application though. For reference, the window would be 1920 / 2 = 960 pixels width. I personally don't think this has anything to do with the minimum width and height.

**Comment by Ralith** [comment]
FWIW, nheko plays just fine in a tiling window manager. In general, X11 window managers can unilaterally clobber the geometry of a window; the window's requests are merely suggestions. Sounds like this is something weird about Xfwm.

**Comment by alphapapa** [comment]
@Ralith I don't think it's that simple.  I use KDE/KWin, and I can't make nheko's window smaller than a certain size.  I don't have this problem with other apps.

**Comment by Ralith** [comment]
It is that simple. It's your WM's decision to respect a minimum size requested by the application.

**Comment by alphapapa** [comment]
Ok, so why is nheko requesting that minimum size?  Here's an example:
![nheko1](https://user-images.githubusercontent.com/601365/34974120-e7973148-fa50-11e7-8894-677445bf61f7.png)
There's plenty of whitespace, so there should be plenty of room for me to make the window smaller.

**Comment by mujx** [comment]
Hmm maybe that minimum size is imposed by the settings page.

**Comment by PureTryOut** [comment]
Preferably nheko acts like Telegram, resizing itself to a mobile layout of some sorts. As @alphapapa showed in his last screenshot, nheko still looks quite good when resized to be that small.

**Comment by alphapapa** [comment]
@PureTryOut You're right, it mostly does.  However, sometimes messages do not get wrapped, and instead they are truncated past the edge of the screen, which also pushes the newly right-aligned timestamps off the screen.  This happens even without overriding the minimum size, though, so I think there's a minor bug.  I haven't discovered a pattern yet, so I haven't reported it yet.
