### ISSUE TITLE
Create release tarballs which also contain the source code of required git submodules

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#189]
This would be very helpful for packaging in Linux distros - the automatically generated tarballs from GitHub don't have the submodules. (Also how about using `.xz` or `.bz2` for better compression?)

**Comment by mujx** [comment]
I have added a script that does this `script/archive.sh`.

**Comment by ollieparanoid** [comment]
Downloaded the `.tar.bz2` and can confirm that it contains everything from the `libs` folder. Excellent, thanks for the quick reaction!

**Comment by Aerdan** [comment]
Slight problem: the archive script needs to include `-j` in order to actually bzip2 the tarball.

**Comment by mujx** [comment]
Thanks for the hint. I updated the script and the release tarball.
