### ISSUE TITLE
Fails to run on windows 10

### ISSUE THREAD

**Issue by clandmeter** [mujx/nheko#192]
Im trying to install the latest v0.1.0 on windows but when I select "Select All" the installer will crash (i guess that's as expected as I see Broken in the details box).

If i install it by Default the application will fail to start with the following msg in event viewer:

```
Faulting application name: nheko.exe, version: 0.1.0.0, time stamp: 0x5a42d7b2
Faulting module name: ucrtbase.dll, version: 10.0.16299.98, time stamp: 0x70f70cc4
Exception code: 0xc0000409
Fault offset: 0x000000000006b70e
Faulting process id: 0x2c20
Faulting application start time: 0x01d38478cd23659e
Faulting application path: C:\Program Files (x86)\nheko\nheko.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: afb2458d-7e38-4bec-b6ad-b7177e54cdcc
Faulting package full name: 
Faulting package-relative application ID: 
```

This is on 
Windows 10 
Version 1709
OS Build 16299.98

Note: I have had previous version(s) installed but not really used before.

**Comment by MTRNord** [comment]
Did you get the warning asking to uninstall the previous Version?

**Comment by clandmeter** [comment]
Yes and i did and after it failed to install cause i used select all and after installed again without select all.

**Comment by MTRNord** [comment]
I will check on my PC if I can reproduce it (and than fix it)

**Comment by MTRNord** [comment]
Ah I See why. :) It start in that case to run the Cleanup Task which shouldn't be run as it isn't working yet. I thought it was disabled and didn't expect that it can be selected by "Select all". A install without using "Select all" should work currently.

**Comment by MTRNord** [comment]
You might need to clear the nheko cache in the Appdata Local folder (named nheko) if it still doesn't start if you had a older version installed previously

**Comment by clandmeter** [comment]
Yes that did it.

Thanks!
