### ISSUE TITLE
Messages got lost

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#194]
### System
- Nheko commit/version: 799885a Add script to create archive
- Operating System: Arch Linux x86_64
- Qt version: 5.10.0-2
- C++ compiler: GCC 7.2.1-2
- Desktop Environment: i3wm

### Actual behavior
I was in #postmarketOS sending 12 messages within a few seconds, each one with a few sentences. That worked fine. I sent a 4 messages over the following 20 minutes, that worked as well.

Between 5 and 6 hours later I am sure I've sent about 5 messages to comment something that came up in the channel, and when I started nheko today scrolling up the backlog, I see that none of them got sent.

Roughly a few minutes before I typed in the messages that could *not* be sent I was able to successfully send messages in other channels though.

I've restarted nheko during this chat session twice or so because of #193 and opened Riot in a web browser while nheko was running. I may have closed it directly before I was unable to send the messages, but I am not sure.

### Expected behavior
All messages get sent - and if they can't get sent, show a warning or something.

I don't know if this is possible with the Matrix protocol, but how about an indicator that shows when a message has been sent? Like the Signal messenger for phones (and from what I've seen from friends, WhatsApp etc. do it the same way) - when your message has been sent, a check mark appears next to it. When it failed to get sent, a red warning icon appears next to it with a button to resend it, and you get a notification.

### Steps to reproduce
That would be nice, right?

**Comment by mujx** [comment]
Related #97, #93.

**Comment by mujx** [comment]
@ollieparanoid Is this still an issue?

**Comment by ollieparanoid** [comment]
I don't think so. The UI has been improved a lot, it's obvious when nheko is offline now, and there are checkmarks for messages that have been sent.

Unrelated note: I'm using the stable builds of nheko that are in Fedora now, not building it from git myself anymore. But I'm still using it almost every day. Thanks for all the fixes, features and for maintaining it :tada:
