### ISSUE TITLE
Windows emoji font not working

### ISSUE THREAD

**Issue by MTRNord** [mujx/nheko#20]
On Windows there is no color at the emoji bar and when adding emojis. Maybe a issue with the used font.

**Comment by JaniM** [comment]
Also they are grayed out in the picker.

**Comment by mujx** [comment]
It would be nice to have a screenshot of the emoji picker for future reference.

**Comment by MTRNord** [comment]
![image](https://cloud.githubusercontent.com/assets/1374914/26029753/4b83c7c4-383d-11e7-8bc3-d4cfb8bb28d8.png)

**Comment by mujx** [comment]
The emoji picker has been removed.
