### ISSUE TITLE
How login to my Homeserver with Identity server from Windows?

### ISSUE THREAD

**Issue by psyapathy** [mujx/nheko#200]
Hello!

Can I login to my Homeserver with Identity server from Windows?
I have local HS and identify server for this.
HS: domain:8008
IS: domain:8090

Where I can use this configs?
Or I need build my own nheko for Windows with this servers in config?

Thank you advance!

**Comment by mujx** [comment]
I'm not familiar with Identify servers but nheko only sends requests to the homeserver. You can specify the port at the login page.

**Comment by mujx** [comment]
I'm closing this as resolved. Feel free to re-open it if you need any more info.
