### ISSUE TITLE
Emoji are oversized

### ISSUE THREAD

**Issue by nvbln** [mujx/nheko#203]
### System:

- Nheko commit/version: 0.1.0
- Operating System: Debian
- Desktop Environment: GNOME

### Actual behavior

This is what it looks like right now:

![screenshot from 2018-01-13 10-41-55](https://user-images.githubusercontent.com/20875906/34904914-3eb2a506-f84f-11e7-9fa2-6e43a1b58bed.png)
The smiley is big even though it is used after text (which I think should result in a small smiley?). Another point is that the smiley seems to be too bug, as parts of the top and bottom are cut off.
![screenshot from 2018-01-13 10-40-05](https://user-images.githubusercontent.com/20875906/34904916-3ecc69a0-f84f-11e7-9dcf-89729579f134.png)
The smileys are big even though the space reserved for them is small. I assume that showing the small smiley is the expected behaviour.
![screenshot from 2018-01-13 10-38-53](https://user-images.githubusercontent.com/20875906/34904917-3ee2da3c-f84f-11e7-9e3d-c565107f5137.png)
This is what a room looks like from the menu when using smileys in the title (and icon).

### Expected behavior

This is what the third image looks like in Riot for example: 

![screenshot from 2018-01-13 10-48-32](https://user-images.githubusercontent.com/20875906/34904924-718a9bbe-f84f-11e7-8e9a-7bea684aaea7.png)

**Comment by PureTryOut** [comment]
Duplicate of #44.

**Comment by nvbln** [comment]
Ah my bad.

**Comment by nvbln** [comment]
In case anyone else finds this issue, I was able to fix it by adding Buster to my apt sources and running `apt install --upgrade-only qt5-qmake`.
