### ISSUE TITLE
New black lines in UI

### ISSUE THREAD

**Issue by alphapapa** [mujx/nheko#207]
I just pulled and built the latest commit, and now there are black lines separating parts of the UI:
![nheko](https://user-images.githubusercontent.com/601365/34963694-7f5ec640-fa0f-11e7-82b4-b503e02f1360.png)

**Comment by mujx** [comment]
Yes this was introduced in https://github.com/mujx/nheko/commit/af5663b6bc5de95ad4e15bcc40231e0094a9889c. This is the default theme which uses the same color as the text.

**Comment by alphapapa** [comment]
Oh.  Well...in a way it's nice, but depending on one's theme, it's kind of jarring.  The timestamps look good right-aligned, though.

**Comment by mujx** [comment]
PRs welcome!
