### ISSUE TITLE
Cannot define a portnumber when try to login an HS

### ISSUE THREAD

**Issue by hurzelmann** [mujx/nheko#21]
I cannot define a portnumber when try to login an HS

**Comment by jansol** [comment]
You can enter it in the settings dialog (cog icon), albeit that is still a bit broken. I'm working on a fix for that whole mess so it should get fixed soon.

**Comment by hurzelmann** [comment]
OK, but once that is set I cannot enter anything in the username field...

**Comment by mujx** [comment]
It should start with a @. The username must be a matrix ID which has the following format `@username:domain`. I will open an issue to fix this because a lot of people get confused.

For now you can add manually the port in your config. On Linux should be located in `~/.config/Nheko/nheko.conf`

**Comment by hurzelmann** [comment]
OK, actually I can (when starting with an @)...

What the necessary format after defining the port in the settings... it stills says "Invalid Matrix ID"...

**Comment by hurzelmann** [comment]
OK, it´s working now... however some improvements here would be very nice as this is not clear for everyone (at least myself... )

**Comment by jansol** [comment]
This should be fixed now with the server address field?
