### ISSUE TITLE
Wrong count of unread messages

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#218]
### System
- Nheko commit/version: 9eedcd7 Remove trailing whitespace from text messages
- Operating System: Arch Linux x86_64
- Qt version: 5.10.0-3
- C++ compiler: GCC 7.2.1+20180116-1
- Desktop Environment: i3wm

### Actual behavior
The unread message count per channel and total is always higher than the actual message count. For example, it says 6 on the channel, and when I click the channel, there's only one new message (it may have multiple lines though, maybe that is related?).

### Expected behavior
Showing the actual unread message count.

### Steps to reproduce
Get messages with nheko in one channel while having another channel selected. Then compare the count it displays with the actual message count.

**Comment by mujx** [comment]
I can't reproduce the issue. Does this happen every time you receive messages?

**Comment by mujx** [comment]
Now it happened to me also. The count gets doubled.

**Comment by ollieparanoid** [comment]
It happened all the time yesterday, I've even restarted `nheko` once to verify.

**Comment by mujx** [comment]
I think this is fixed by 86aa409c1f27a7cfed181934a13e8c4a7b016df1. Can you confirm?

**Comment by ollieparanoid** [comment]
Yep, it's fixed. Thank you very much! \o/
