### ISSUE TITLE
Improve login UX

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#22]
Currently the username field requires the input to start with a @ but most people are not used to typing the whole matrix id to login and that creates some confusion.

One possible solution would be to validate the input while the user is typing (without the automatic regex validator) and then add any missing @ behind the scenes.

For example both of the following inputs should be valid:
- `user:matrix.org`
- `@user:matrix.org`

**Comment by jansol** [comment]
I was thinking of adding the @ automatically if the user enters something without it. I'll experiment with this as part of my server handling improvements (since that alters the login flow a bit code-wise)

**Comment by mujx** [comment]
Actually we don't need the @ at all. It should be optional in case a user decides to use the full matrix id format.

**Comment by z3ntu** [comment]
Quick question: Why do the buttons have random `&` signs in them? (app looks great already btw)

**Comment by mujx** [comment]
@z3ntu do you use KDE by any chance? It might be related to #14

**Comment by z3ntu** [comment]
Yes I do.

**Comment by PureTryOut** [comment]
As I mentioned a few days ago in [#nheko:matrix.org](https://matrix.to/#/!BPvgRcBVHzyFSlYkrg:matrix.org/$1499516047811365IingY:matrix.org), you could also add a read-only @ in front of the username input box. Basically like Riot had for a while.
