### ISSUE TITLE
HTTP errors when failing to log in on login screen don't wrap, causing window to expand to be ~3000px wide

### ISSUE THREAD

**Issue by ara4n** [mujx/nheko#222]

**Comment by mujx** [comment]
A screenshot would be helpful to understand what the problem is.

**Comment by ara4n** [comment]
<img width="4708" alt="screen shot 2018-01-30 at 18 16 50" src="https://user-images.githubusercontent.com/1294269/35583421-c79d725e-05e9-11e8-80f8-c16646237427.png">

**Comment by ara4n** [comment]
<img width="4708" alt="screen shot 2018-01-30 at 18 16 50" src="https://user-images.githubusercontent.com/1294269/35583520-1fcc1020-05ea-11e8-8cf2-935055f4f795.png">

**Comment by mujx** [comment]
This should be replaced with an error message. The full URI shouldn't be there.

**Comment by ara4n** [comment]
you certainly shouldn't be leaking access tokens anywhere in the UI :)

**Comment by mujx** [comment]
This has been addressed by displaying the error message returned by the homeserver.
