### ISSUE TITLE
Make release error on Mac OS

### ISSUE THREAD

**Issue by MattiooFR** [mujx/nheko#226]
Hi,

I tried to install Nheko on Mac OS High Sierra, but I got an error when I do the make release command : 

> make: cmake: No such file or directory
> make: *** [release] Error 1

I tried -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/ but I got : 
> No such file or directory

Can you help me out ?

### System:

- Nheko commit/version: Last version
- Operating System: Mac OS High Sierra 10.13.3
- Qt version: qt5
- C++ compiler:

**Comment by mujx** [comment]
Did you install cmake?

**Comment by MattiooFR** [comment]
Thanks for your reply it worked !
But now during the make release an error occured : 

> CMake Error at CMakeLists.txt:57 (find_package):
>   By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Qt5Widgets", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Widgets" with
>   any of the following names:
> 
>     Qt5WidgetsConfig.cmake
>     qt5widgets-config.cmake
> 
>   Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
>   "Qt5Widgets_DIR" to a directory containing one of the above files.  If
>   "Qt5Widgets" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/mattioo/nheko/build/CMakeFiles/CMakeOutput.log".
> make: *** [release] Error 1

**Comment by mujx** [comment]
Did you try adding `-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/<qt_version>`?

**Comment by MattiooFR** [comment]
Where do I add this ? In the make release ?

Like 
> make release -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.10.0_1 ?

**Comment by ara4n** [comment]
I had the same problem (again) when building to show off nheko at FOSDEM yesterday.   I ended up manually running `cmake -DCMAKE_BUILD_TYPE=Release` and then `make` to build it - I didn't need to put a CMAKE_PREFIX_PATH, but the current instructions certainly don't work.

**Comment by MattiooFR** [comment]
Grr, I don't k now why but still an error : 

> mattioo$ cmake -DCMAKE_BUILD_TYPE=Release
> -- The C compiler identification is AppleClang 9.0.0.9000039
> -- The CXX compiler identification is AppleClang 9.0.0.9000039
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found LMDB: /usr/local/include  
> CMake Error at CMakeLists.txt:57 (find_package):
>   By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Qt5Widgets", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5Widgets" with
>   any of the following names:
> 
>     Qt5WidgetsConfig.cmake
>     qt5widgets-config.cmake
> 
>   Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
>   "Qt5Widgets_DIR" to a directory containing one of the above files.  If
>   "Qt5Widgets" provides a separate development package or SDK, be sure it has
>   been installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/mattioo/nheko/CMakeFiles/CMakeOutput.log".

**Comment by MattiooFR** [comment]
I found out that it worked with this command : 

> cmake -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)
