### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by ghost** [mujx/nheko#230]
I would like to see nheko support a scaling factor mechanism. This could be represented in the configuration screen via a slider with increments of 25% from perhaps 50% or 100% up to 400%. The scale factor would be used to scale the UI up (or down, for <100% factors) in order to make the application more usable for low-vision users such as myself.

Other software which provides such a feature includes:
* Telegram
* Discord
* Any web client with a responsive UI design.

**Comment by thomas-profitt** [comment]
Running the application with the `QT_SCALE_FACTOR` environment variable set to a value other than 1 does this well. Can this same behavior be set from within the app while it's running?

**Comment by alexforencich** [comment]
+1, this would be great for high DPI monitors
