### ISSUE TITLE
Add room settings menu

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#235]
The menu could also show some basic info about the room (e.g number of users)

Example settings:
  - Notification preferences
  - Change name/avatar/topic

**Comment by ollieparanoid** [comment]
Related: #65

**Comment by PureTryOut** [comment]
This can be closed now 3097037c3dc882be2efe64dce6aefeea43d5f040 is in right?

**Comment by mujx** [comment]
Not sure if we should wait to add an option there to change the name & topic.
