### ISSUE TITLE
Unread notifications shown for channels where it is disabled

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#236]
### System
- Nheko commit/version: f95998a Be explicit about the captured parameters in lambdas
- Operating System: Arch Linux x86_64
- Qt version: 5.10.1-1
- C++ compiler: GCC 7.3.0-1
- Desktop Environment: i3wm

### Actual behavior
I get notifications about unread messages for a few channels, where it is disabled. When I right click these channels, it says "Enable notifications" in the menu, indicating that it is disabled.

### Expected behavior
Not getting unread message notifications for channels where it is disabled.

**Comment by mujx** [comment]
The notifications are server-side now, so you'll have to configure them through Riot, until there is a ui on nheko. That means you can also receive notifications for mentions & keywords. The 'Enable notifications` button doesn't do anything currently.

**Comment by mujx** [comment]
The option has been removed. You can follow #317 which will solve this issue.
