### ISSUE TITLE
Feature: Option to put names on the left of messages

### ISSUE THREAD

**Issue by thinslice** [mujx/nheko#243]
Please add an option to put names of people besides the messages.
I like this arrangement the most.

Images of this:

http://www.adiumxtras.com/images/pictures/ymous_5_366_5474_image_9725.png

https://assets.pcmag.com/media/images/200759-skype-4-0-the-new-look.jpg

**Comment by NotAFile** [comment]
'The motivation behind the project is to provide a native desktop app for Matrix that feels more like a mainstream chat app (Riot, Telegram etc) and less like an IRC client.'

**Comment by mujx** [comment]
I'll have to close this one, since this is a feature that resembles more an IRC client which is what nheko tries to avoid.
