### ISSUE TITLE
Feature request: Home/End/Page{Up,Down}/Arrow keys keys in rooms list

### ISSUE THREAD

**Issue by unclechu** [mujx/nheko#244]
I have account with 150+ rooms and it's very hard to scroll it only using wheel on my mouse.
I realized I could use mouse wheel with Ctrl/Shift pressed that scrolls it by pages, but I think it would be better if keyboard experience would be improved somehow. I know that that keys in topic used in message input field but maybe with some prefix or by moving focus it could work.

**Comment by mujx** [comment]
There is a simple room switcher. You can open it with ctrl-K. 

There isn't fuzzy matching at the moment so you'll have to be accurate. For example if you want to search for irc rooms you'll have to start with `#`.

**Comment by unclechu** [comment]
@mujx oh, that's better, but it has UI bug, I don't see what I type, only suggestions, because it doesn't use system colors, text is white and background is white.

**Comment by unclechu** [comment]
I created an issue for that: mujx/nheko#245

**Comment by mujx** [comment]
Closing this as resolved by the room switcher.
