### ISSUE TITLE
UI: Leave room confirmation text exceeded window width

### ISSUE THREAD

**Issue by unclechu** [mujx/nheko#247]
![screenshot from 2018-02-24 17-52-32](https://user-images.githubusercontent.com/799353/36630649-bcbaf1e4-198b-11e8-893b-64dbba2628b9.png)
System font: [Hack](https://github.com/source-foundry/Hack)
Commit: 75208de6e8599a30223dad33a78000008eed2a8f

**Comment by mujx** [comment]
How did you override the app font (Open Sans) ?

**Comment by unclechu** [comment]
@mujx I just set font in QT settings (`qt5ct` app).

**Comment by unclechu** [comment]
Anyway, I don't thing we should set window width relying on approximate font size. At least it could be line-breaking in this modal window.

**Comment by mujx** [comment]
This should have been fixed with 3d2e29bfa0ec0ad387064e31e8fcd69097b9a560. Could you confirm?

**Comment by unclechu** [comment]
@mujx Now I can't reproduce it, text always fit the modal's window. I guess it is fixed.

**Comment by mujx** [comment]
Thanks!
