### ISSUE TITLE
UI: Invite buttons is unreadable

### ISSUE THREAD

**Issue by unclechu** [mujx/nheko#248]
As in mujx/nheko#245, background of buttons is white as text is:
![screenshot from 2018-02-24 17-59-41](https://user-images.githubusercontent.com/799353/36630716-b5f6e448-198c-11e8-8a2e-9f5e1b8bd5e7.png)

**Comment by mujx** [comment]
Are you using a custom qt theme?

**Comment by unclechu** [comment]
@mujx I'm using `Adwaita-Dark` which included to Fedora Workstation 25.

**Comment by unclechu** [comment]
In the nheko I set using "system" theme.
