### ISSUE TITLE
Add a way to join/leave/create a room

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#25]
- [x] Join a room
- [x] Leave a room
- [ ] Create  room

**Comment by simoniz0r** [comment]
Is joining a room supposed to be done through the plus button below the channel list?  On both the AppImage and with the latest deb release, this button does nothing, so I'm kinda confused as to how this is supposed to work.

**Comment by mujx** [comment]
@simoniz0r Currently the only way to join a room is through the `/join <room_id>` command. But in the future a gui option would be available. Those buttons are just placeholders for now.
