### ISSUE TITLE
Emoji popover only disappears if the mouse cursor has entered it once

### ISSUE THREAD

**Issue by NotAFile** [mujx/nheko#254]
If you hover over the emoji button, a popover appears. If you enter the popover and leave it again, it works as expected. But in some cases, e.g. when sliding your mouse to another window, you might not actually enter the popover. In that case, the popover stays in position until you move your mouse into and out of it again.

Nheko version: 0.1.0

**Comment by mujx** [comment]
Could you try the latest version and let me know if the problem persists?

**Comment by NotAFile** [comment]
Yup, happens with current master.
