### ISSUE TITLE
Login doesn't work with a custom homeserver port

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#256]
If the user specifies a custom homeserver domain name with a port (e.g `matrix.example.org:8448`), nheko will still use the default 443 port and as a result it won't be able to connect.

**Comment by mujx** [comment]
Closing as invalid. It was self-signed certificate issue.

**Comment by MTRNord** [comment]
@mujx wouldnt it make sense to have a Start Option that allows to allowed selfsigned certs?(as people might test dendrite on their local PC)

**Comment by mujx** [comment]
@MTRNord Yeah, I was thinking about that use cas. I switch manually to test http endpoints. 

A flag that will accept insecure connections & http would be helpful.
