### ISSUE TITLE
Only mark my own messages as read on server

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#261]
In previous `nheko` versions, it did not send read notifications to the server, but only kept them locally. For me this had two advantages:
* Unread message notifications instantly go to 0 when clicking on a channel (no need to wait for the server to acknowledge that, which takes up to a few seconds now).
* Others in the channel did not see what messages I have "read".

The latter was nice and important for me, because just because I give focus to `nheko`'s window or if I click on a channel doesn't mean that I have really read the entire thing. I don't want my user's profile picture to appear in Riot next to the messages I may or may not have read and get people excited about me writing back if they asked me something because of that. It might be that I don't really have time to answer at that point and I'll answer later. When people see that I probably have read the message (only because I gave focus to nheko's chat window doesn't automatically mean I actually read everything on screen!), they may think I'm ignoring them which isn't good.

In order to "fix" that, I came up with the following:
* Add a new setting "only mark my own messages as read on the server"
* When that is set, get the unread messages from the server as usually (so we get the mentions properly)
* Instead of sending to the server when a message has been read, just reset the unread messages counter for that channel locally
* When I write a message, then set that message as read on the server (or the one above, if that is not possible)

Does this make sense, and would something like that get accepted in `nheko`?

**Comment by mujx** [comment]
I agree that it's not ideal to send a read notification just the moment you click on the room. It should somehow detect user activity. But even with some more sophisticated user activity detection you would still have the same problem. Correct me if I'm wrong.

The first bullet point on your suggestions is automatically done by the server. When you send a message is marked as read by you, so what could be done is to set an option to disable automatic read notifications and have a context menu on each message that will allow you to send the read notification manually. 

The notification count would not be changed manually tho, it would still be managed by the server. So you would be able to enter a room and no one would know that you read something unless you send a message or click `read message` on the context menu. Depending on which action you did the notification count would be updated accordingly. Let me know if that sounds ok.

**Comment by ollieparanoid** [comment]
> Let me know if that sounds ok.

Yes, that sounds like a good solution! :smiley:

**Comment by ollieparanoid** [comment]
Awesome, thanks @mujx! :tada: :tada:
