### ISSUE TITLE
Register not possible

### ISSUE THREAD

**Issue by amittel** [mujx/nheko#264]
### System:

- Nheko commit/version: 0.2.0
- Operating System: Win10 x64
- Qt version:
- C++ compiler:
- Desktop Environment: 

### Actual behavior
New to Matrix and wanted to register. Filled out the form and hit register. But I get an error like "Host requests an authentication" and nothing happens.
As home server I used matrix.org

### Expected behavior
Register and start exploring.

### Steps to reproduce
Try to register.

**Comment by mujx** [comment]
Registration doesn't work on matrix.org, because it requires you to fill a captcha which isn't currently possible to be done through nheko. You would have to register through Riot.

**Comment by anoadragon453** [comment]
@mujx Have you seen the [fallback API](https://matrix.org/docs/spec/client_server/r0.3.0.html#fallback) which allows you to direct a user to a page on the homeserver in a web browser where they will complete the ReCaptcha step?

**Comment by mujx** [comment]
@anoadragon453 I don't see how it's possible to get that session id in the app without embedding a webview.

**Comment by anoadragon453** [comment]
The session ID is returned as part of the call to [/register](https://matrix.org/docs/spec/client_server/r0.3.0.html#user-interactive-api-in-the-rest-api).

Thus if the server responds with a register flow containing a stage requiring a webview (such as `m.login.recaptcha`) then you'd just open the default web browser on the device and point it to `/_matrix/client/r0/auth/m.login.recaptcha/fallback/web?session=<session ID>`.

Then have a button for "I did it" and try the registration again.

**Comment by mujx** [comment]
Thanks @anoadragon453, that seems easy enough.
