### ISSUE TITLE
Create an Ubuntu or Debian repository

### ISSUE THREAD

**Issue by ghost** [mujx/nheko#266]
It would be more convenient if every week I did not have to check github in search of a new update and download it apart from the general update of applications of my system to install it.

**Comment by lammel** [comment]
The nheko package is already available in Debian Testing, although an outdated git version from Nov 2017. See https://tracker.debian.org/pkg/nheko

Having upstream would be the preferred solution of course, but puts the strain on the Matrix Packaging Team.

**Comment by mujx** [comment]
Any help is appreciated regarding deb package because I'm not really familiar with the build procedure.

**Comment by lammel** [comment]
It would probably make sense to contact the debian maintainer and maybe pull the changes upstream (actually it is more or less copying the debian/ directory) to allow an automatic debian build. Not sure if that helps maintaining for Debian or not.

The debian repository with Debian patches: https://salsa.debian.org/matrix-team/nheko

I've created a fork of the debian tracking repository here: https://salsa.debian.org/random-guest/nheko to look getting a more recent build and provide a pull request for the debian maintainer.

**Comment by CitoplasmaX** [comment]
Maybe you can use Debreate. https://antumdeluge.github.io/debreate-web/

**Comment by MTRNord** [comment]
Pinging @uhoreg as according to the tracker link he published nheko upstream so I guess he might be interested in this Issue.

**Comment by uhoreg** [comment]
FWIW, an updated version of the package in Debian is waiting on me uploading version 3 of nlohmann's json library.

**Comment by uhoreg** [comment]
I've built packages for nheko 0.2.1.  I have one more packaging issue to fix, but hopefully I'll have it in my personal repository some time next week.  Getting it into Debian should happen shortly after my nlohmann-json3 package gets accepted.

**Comment by mujx** [comment]
Flatpak is also available in Ubuntu/Debian as an easy way to install nheko.

**Comment by mujx** [comment]
Closing because the debian repository is already there. It's mostly a matter of pushing the latest version.
