### ISSUE TITLE
Chat window scroll bar disappears randomly

### ISSUE THREAD

**Issue by Qwertie-** [mujx/nheko#270]
### System:
OS: Fedora 27
Package version: nheko-0.2.0-1.fc27.x86_64 (from fedora repo)

### Actual behavior
Scroll bar seems to disappear randomly. Still works, just doesn't display.
### Expected behavior
Scrollbar to show when scrolling
### Steps to reproduce
Not quite sure but it happens every time on my system

![scrollbug](https://user-images.githubusercontent.com/6601505/37395359-fd5469b8-27c5-11e8-8be2-65b47c8a3a88.gif)

**Comment by mujx** [comment]
There is a qt bug (or with nheko) on v5.10.1 & v5.9.4 affecting the property animations (which is used on the scrollbar). It works fine on builds with different qt versions.

**Comment by Qwertie-** [comment]
Ok I worked out how to reproduce it, scrolling 1 click on my mouse brings up the scroll bar, if I stop and wait for it to fade and scroll again it shows again, if I scroll more than 1 click the scroll bar disappears until I wait a bit and then it shows again to fade out.
