### ISSUE TITLE
It does not work Debian based os build

### ISSUE THREAD

**Issue by CitoplasmaX** [mujx/nheko#275]
### System:

- Nheko commit/version: 0.2.1
- Operating System: Trisquel 7 / Ubuntu Trusty (14.04)
- Qt version: 5.2.1
- C++ compiler: GCC 4.8.5
- Desktop Environment:  Gnome Flashback

### Actual behavior
It does not work with the following error:

echedey@echedey-500-500ns:~$ nheko
nheko: /lib/x86_64-linux-gnu/libgpg-error.so.0: no version information available (required by /tmp/.mount_nhekoDVWOLY/usr/bin/../lib/libgcrypt.so.20)
nheko: relocation error: nheko: symbol _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

### Expected behavior
I experted it works, I have no problem with previous version (0.2.0).

**Comment by mujx** [comment]
Did you use the AppImage?

**Comment by CitoplasmaX** [comment]
No, i am using .deb package

**Comment by mujx** [comment]
@CitoplasmaX Could you try downloading it again from the releases page. I have updated it.

**Comment by CitoplasmaX** [comment]
okay

**Comment by CitoplasmaX** [comment]
It works now. Thank you.
