### ISSUE TITLE
32bit support for Ubuntu

### ISSUE THREAD

**Issue by dikiaap** [mujx/nheko#281]
nheko is pretty cool and I want to try it.
How can I install nheko on 32-bit system? I see on the release page there is no 32-bit .deb packages.

**Comment by mujx** [comment]
For now the only possible solution would be to build it yourself because there are no pre-built packages.

**Comment by dikiaap** [comment]
Well, I think it has a lot of dependence on it, specifically Clang. I will wait in the future if it's possible.
