### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by KSXGitHub** [mujx/nheko#283]

**Comment by vurpo** [comment]
Also related: HTML support, to display formatted messages as formatted

**Comment by KSXGitHub** [comment]
@vurpo Markdown does have HTML in it.

**Comment by vurpo** [comment]
Markdown can have HTML in it, but I mean the client never receives Markdown formatted messages from the server, all messages that it receives are either HTML formatted or completely unformatted. Markdown support would be to support _sending_ formatted messages, but not display _received_ formatted messages.

**Comment by dessalines** [comment]
Would love to see this.

- Markdown support
- Replies
- Mentions
