### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by loru** [mujx/nheko#284]
### System:

- Nheko commit/version: 0.2.1
- Installation method: 
- Operating System: OSX 10.12 Sierra

### Actual behavior
Clicking on login, filling up @myuser:local.domain that is self signed
Filling up password
Homeserver appears: filling up local.domain

-> Cannot connect to the server. The setup works with Riot. The certificate is self signed, valid on time.
Error: "SSL handshake failed". 

How can I give more info about this? Help help help. :P

**Comment by mujx** [comment]
It's not possible to login into a server with a self-signed certificate atm without editing the code. Related issue #260 on the current milestone.
