### ISSUE TITLE
#alpine-linux channel is called PureTryOut and 121 others

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#288]
### System
- Nheko commit/version: 3afc76d Adjust CMakeLists to make dependency downloading optional
- Installation method: local build
- Operating System: Arch Linux x86_64
- Qt version: 5.10.1-6
- C++ compiler: GCC 7.3.1+20180312-2
- Desktop Environment: i3wm

### Actual behavior
A few days ago, the "Alpine Linux" channel switched its name to "PureTryOut and NNN others" (NNN being the number of users, PureTryOut is the matrix username of @PureTryOut). It also uses his profile picture instead of the usual channel logo. This is still happening, although I've restarted `nheko` multiple times.

I've just checked now, and in the Riot webinterface, the channel is still called Alpine Linux and has the proper logo.

### Expected behavior
Channel name and icon like in Riot web.

### Steps to reproduce
No idea, sorry.

**Comment by mujx** [comment]
The cache had a major refactoring (more robust implementation) and its format changed. Hopefully there won't be any other incidents like this, but I'll leave the issue open to track them.

**Comment by ollieparanoid** [comment]
Awesome, thanks!

**Comment by mujx** [comment]
FYI just realized this is server (i.e synapse) issue (state reset) and it also affecting Riot and other clients. There isn't much we can do at the client level.
