### ISSUE TITLE
Tray applet -> Quit doesn't work

### ISSUE THREAD

**Issue by z3ntu** [mujx/nheko#30]
The window hides but it's still running in the background.

**Comment by z3ntu** [comment]
I'm gonna post some other more-or-less small things here (don't want to create an issue for them):

* That error:
```
Unknown message type QJsonObject({"content":{},"event_id":"$1494863127180157eibVM:matrix.org","origin_server_ts":1494863127455,"sender":"@werner.noebauer:matrix.org","type":"m.room.message","unsigned":{"age":530837434,"redacted_because":{"content":{},"event_id":"$1494863295182028QVaEn:matrix.org","origin_server_ts":1494863295755,"redacts":"$1494863127180157eibVM:matrix.org","sender":"@werner.noebauer:matrix.org","type":"m.room.redaction","unsigned":{"age":530669134}},"redacted_by":"$1494863295182028QVaEn:matrix.org"}})
```

* No tray applet **icon**
* Profile pic is stretched
* The roomnames are white (Breeze Dark theme on KDE)
![image](https://cloud.githubusercontent.com/assets/3768500/26286685/d663aa92-3e6b-11e7-808d-039154d76c42.png)

**Comment by PureTryOut** [comment]
> don't want to create an issue for them

Why not? If they're not related to the issue here than they should be posted separately. 


Anyways this issue seems to happen if the window is not closed when you press quit in the tray. If you first close the window by pressing the X, and then use the quit option in the tray it works fine. So I guess that's a workaround for now, but this should definitely be fixed.

**Comment by mujx** [comment]
That's the intended behavior. If the window is visible and you click quit it hides it; if it's not visible the app quits. I will probably change it if anyone else finds it weird.

The unknown message isn't a problem. Some events are not properly spec'd and they are ignored.

The white font issue belongs to #14. I will be more specific with the painting tho. I suspect the no tray icon issue might be related to KDE too.

**Comment by z3ntu** [comment]
What I tried: Open it (run ./nheko) -> press login -> close the window with the X -> right-click tray applet -> Quit -> nothing happens.

**Comment by z3ntu** [comment]
Well "Quit" should be "Quit" and not "hide" 😉
