### ISSUE TITLE
Integrate with libqmatrixclient?

### ISSUE THREAD

**Issue by peterhoeg** [mujx/nheko#311]
Now that libqmatrixclient is getting closer to a stable API (and ABI), is there any chance to use that?

**Comment by MTRNord** [comment]
Afaik mujx seems to plan to use his own https://github.com/mujx/mtxclient instead of libqmatrixclient

**Comment by mujx** [comment]
Like @MTRNord said, the plan is to use mtxclient (which doesn't depend on Qt) when encryption is in a working state. Integration with libmatrixclient would be difficult at this point because nheko uses different types for representing the different matrix structs which are also not based on Qt.

**Comment by peterhoeg** [comment]
:+1:
