### ISSUE TITLE
Improve visibility of unread rooms

### ISSUE THREAD

**Issue by PureTryOut** [mujx/nheko#313]
Right now the rooms are ordered based on activity, which in itself is already a really good thing. However, it's still not always clear which rooms have new activity since the last time I've read them. I seem to remember that room names (in the room list) were bold in the past, but I might be mistaken. I'd like that to be the case again, so I can easily distinguish read rooms from unread rooms.

**Comment by ptman** [comment]
I'm not sure if this is related, but it seems that nheko doesn't keep read/unread status in sync with other clients. Or am I mistaken?

**Comment by PureTryOut** [comment]
It's unrelated, and I think you're mistaken as I recall that being implemented a while ago.

**Comment by mujx** [comment]
@ptman The app sends read receipts, so the server and other clients use them to keep track of the read events. What doesn't work on your case?

**Comment by ptman** [comment]
I'm not sure if this is the right place to discuss this, but I have riot.im/develop and nheko open with the same account at the same time. riot shows rooms with unread messages in bold while nheko shows all rooms the same way giving no hint about unread rooms.

**Comment by mujx** [comment]
Yes that's what this issue is about. There is no *visual* hint.

**Comment by ptman** [comment]
didn't there use to be?

**Comment by mujx** [comment]
Nope, @PureTryOut mentioned that the rooms were bold in the past but that was just the styling, it had nothing to do with unread messages.
