### ISSUE TITLE
Autocompletion popup closes when a new letter is typed

### ISSUE THREAD

**Issue by PureTryOut** [mujx/nheko#314]
To filter the list of matching nicknames, I like to keep typing till a smaller list matches my autocompletion criteria. So whenever the popup first appears, most of the time it means I'll press another character to filter it. However, at this point the popup closes itself till I type another letter. This looks really broken and because of the speed at which I was typing, at first I thought autocompletion didn't work at all.

**Comment by mujx** [comment]
I still can't reproduce. I just run the latest AppImage on Arch Linux with GNOME and the popup doesn't close.

**Comment by PureTryOut** [comment]
How the... Can I somehow debug this myself? Note that I can't recompile for myself.

**Comment by PureTryOut** [comment]
Just tested with the latest nightly AppImage, it is not.
