### ISSUE TITLE
Ctrl+K rooms navigation: avoid pressing Tab

### ISSUE THREAD

**Issue by unclechu** [mujx/nheko#316]
Release: Nightly - f1b355f7a718d132f28b60d7989ce50564052fbc
Earlier, before fuzzy implementation, when I type some room name and press Enter it navigates to the first matched room but now I need explicitly select it by Tab otherwise by Enter it won't change anything, just closes room search modal window. Don't you think it would be better to go to the first match by pressing Enter and do nothing if I press Escape?

**Comment by mujx** [comment]
Yes that's a regression.

**Comment by unclechu** [comment]
I also realized that Shift+Tab for backward selection isn't working too but it may be not a regression but feature request.
