### ISSUE TITLE
Save timeline messages in cache

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#325]
This will greatly improve boot up times because we won't have to wait for the first sync to complete.

Things to consider for the implementation:
 - A valid `from` token must exist so we can paginate backwards
 - We should keep only a part of the timeline and delete old messages.

**Comment by PureTryOut** [comment]
I'm not sure how to best go for it, but I'd cache as much as needed to at least fill the timeline on the screen (without scrolling). This of course depends on screen resolution and how much fits on it, but it'd be a much better user experience.

**Comment by mujx** [comment]
Implemented in 4344b6964f63921aa300112bc3b62fdbaa64866a
