### ISSUE TITLE
No desktop notifications for new messages

### ISSUE THREAD

**Issue by z3ntu** [mujx/nheko#33]

**Comment by PureTryOut** [comment]
Please note that this should happen only to rooms that are configured to do so.

A configuration option to change notification settings to go along with this would be nice, a bit like Riot:
![screenshot_2017-05-22_17-08-30](https://cloud.githubusercontent.com/assets/1565836/26315418/6d980bec-3f11-11e7-9eb5-1d2b5aa9c2d6.png)

**Comment by mujx** [comment]
[snorenotify](https://github.com/KDE/snorenotify) seems like a good solution.
