### ISSUE TITLE
Number of unread messages does not always fit in the circle

### ISSUE THREAD

**Issue by vthriller** [mujx/nheko#330]
### System:

- Nheko version: 0.4.0-03c5f79 (03c5f795432962f13155a5a3fe539d39c08da62a straight from the master branch)
- Installation method: `make release && ./build/nheko`
- Operating System: Gentoo Linux
- Qt version: 5.7.1
- C++ compiler: `gcc version 5.4.0 (Gentoo 5.4.0-r3 p1.4, pie-0.6.5)` (yeah, I know that's old)
- Desktop Environment: none (i3wm)

### Actual behavior

The title of this (admittedly silly) issue says it all; here's a very extreme example (over 19k messages) just to illustrate the point:

![image](https://user-images.githubusercontent.com/176062/40381362-30268690-5e04-11e8-8d5d-9fa93feb8a9b.png)

Three-digit counters barely fit though, but I might be lucky with the fonts installed on my system:

![image](https://user-images.githubusercontent.com/176062/40381787-525c9f64-5e05-11e8-8612-e7e962448c84.png)

### Expected behavior

Abbreviated counters, circles ditched for rectangles with rounded corners, whatever.

### Steps to reproduce

Join some crowded room and forget about Matrix for a week or so.

### Debugger backtrace 

*none*

**Comment by mujx** [comment]
Using `99+` with a circle big enough to contain 3 characters would probably be enough.
