### ISSUE TITLE
Chat text in dark theme is black now (harder to read)

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#331]
### System
- Nheko commit/version: ec7b3e1 Bump version to 0.4.1
- Installation method: local build
- Operating System: Arch Linux x86_64
- Qt version: 5.10.1-8
- C++ compiler: GCC 8.1.0-1
- Desktop Environment: i3wm

### Actual behavior
I have the dark theme activated, and the text in the chat window below the usernames is black now. the usernames are light gray, which is nice to read on the dark background. But the black text color doesn't make a good contrast.

### Expected behavior
A lighter color, I believe it was white or light gray before just a few days ago.

### Steps to reproduce
Build and run the mentioned commit, look into the chat.

**Comment by mujx** [comment]
That is a regression from the last commit on that release (forgot to test the dark theme). A new release is coming with the fix.

**Comment by ollieparanoid** [comment]
Thanks for fixing all the bugs :tada:
