### ISSUE TITLE
Broken rendering on high DPI displays on Windows

### ISSUE THREAD

**Issue by tiffany352** [mujx/nheko#335]
### System:

- Nheko version: Latest release and latest nightly both repro it.
- Installation method: The installer exe.
- Operating System: Windows 10

### Actual behavior

This is a Dell XPS 13 with a 13.3" 3200x1800 display, around 250 DPI. It's configured out of the box to use a UI scale factor of 250%.

![image](https://user-images.githubusercontent.com/1254344/41324514-c10c9206-6e69-11e8-8527-e995c43f02ba.png)

### Expected behavior

For the UI to be readable without a magnifying glass.

In my (limited) experience working with Qt apps, this can be fixed by enabling AA_EnableHighDpiScaling before creating the QApplication.

Enabling compatibility mode so that the application gets bitmap upscaled would "fix" it, but I'd sooner use another client instead.

**Comment by mujx** [comment]
@tiffany352 Could you test if this build (https://bintray.com/mujx/matrix/nheko/hdpi-scaling-test/#files/nheko/hdpi-scaling-test) works?

**Comment by nermolov** [comment]
HiDPI scaling does not work on master for me either (Arch, i3). That test build above works but scales too greatly - I have a 1440p display (not 4K) and as such 2x scaling ends up looking like a toy.

**Comment by dessalines** [comment]
This is still broken on arch.
