### ISSUE TITLE
Submit to Flathub

### ISSUE THREAD

**Issue by bertob** [mujx/nheko#337]
Have you considered submitting nheko to [Flathub](http://flatpak.org/)? It's basically an app store for GNU/Linux, using the distribution-independent [Flatpak](http://flatpak.org/) package format. This means that nheko would instantly be available on every major distribution. We're using Flathub as the primary distribution mechanism for Fractal, and it's awesome :)

**Comment by mujx** [comment]
There is already (somewhat outdated now) a [package](https://github.com/vrutkovs/flatpak-nheko) that I wanted to submit on Flathub but never got to it.

**Comment by qazip** [comment]
Is there any news regarding this? I'd like to be able to easily install this on ubuntu 16.04 and having to install ppas to compile in every machine is so annoying..

**Comment by mujx** [comment]
@qazip I have a flatpak manifest that builds the app but it fails to run due to misplaced shared libraries.

Btw e2ee is not done, they are still pieces missing.

**Comment by mujx** [comment]
PR submited. https://github.com/flathub/flathub/pull/522
