### ISSUE TITLE
Cannot login to my HS

### ISSUE THREAD

**Issue by hurzelmann** [mujx/nheko#34]
The spinner stays active for ever. 
The following message is in the terminal:

qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
qt.network.ssl: Error receiving trust for a CA certificate
"Connection refused"
Profile: Response is not a JSON object

Login with riot to my HS is working fine.

**Comment by z3ntu** [comment]
Probably related / duplicate of #12

**Comment by mujx** [comment]
What is the setup of your HS? Does it use the standard 443 port? (nheko only supports https connections).

**Comment by hurzelmann** [comment]
I use port 8448 via Riot Android anderen Riot Web

**Comment by mujx** [comment]
@hurzelmann Isn't this the same problem with #21?

**Comment by hurzelmann** [comment]
Yes, at the end I  cannot login to my HS... ☺

**Comment by hurzelmann** [comment]
...with nheko

**Comment by mujx** [comment]
Currently there is no way to set a custom port unless you add it manually to your config `~/.config/Nheko/nheko`.

```
[auth]
...
home_server=domain.com:8448
...
```

**Comment by hurzelmann** [comment]
maybe stupid question:

Where can I find nheko.conf when build ran on a Mac?

**Comment by z3ntu** [comment]
According to Qt documentation it should be at the same location (so `$HOME/.config/Nheko/nheko.conf`)

**Comment by mujx** [comment]
The `Error receiving trust for a CA certificate` errors pointed by @z3ntu is a qt bug on mac and it's harmless.

 Closing this as duplicate of #21. If you have more questions ask there or at the matrix room :)
