### ISSUE TITLE
 Initial sync error: [json.exception.out_of_range.406] number overflow parsing

### ISSUE THREAD

**Issue by albjeremias** [mujx/nheko#342]
### System:

- Nheko version: https://aur.archlinux.org/packages/nheko-git/ - nheko-git 0.4.3.r680.604cdce-1
- Installation method: trizen -S nheko-git
- Operating System: Archlinux

### Actual behavior
On my first login:
```
 0.091: [debug] - D-Bus system tray: no
     0.101: [debug] - palette support is disabled
     0.101: [debug] - custom style sheet is disabled
    22.142: [debug] - Setting up cache
    22.142: [debug] - First time initializing LMDB
    22.159: [info] - Deleting cache data
    22.160: [debug] - Setting up cache
    22.160: [debug] - First time initializing LMDB
    29.860: [debug] - Invalid format for community avatar  ""
    29.861: [debug] - Invalid format for community avatar  ""
    82.407: [debug] - Error code received 504
    82.407: [warning] - Retrying initial sync
   142.490: [debug] - Error code received 504
   142.490: [warning] - Retrying initial sync
   202.117: [warning] - Initial sync error: [json.exception.out_of_range.406] number overflow parsing
```
### Expected behavior
I should be able to login! :) but it seems it overflows...?

### Steps to reproduce
login to my account! ;)

**Comment by mujx** [comment]
IIRC there was a bug where a huge number was set for a power level in synapse. Are you by any chance in one of those rooms?

**Comment by albjeremias** [comment]
maybe... how can I debug that?

**Comment by mujx** [comment]
@albjeremias Just leave that room.

**Comment by albjeremias** [comment]
i dunno which room it is.. :(

**Comment by mujx** [comment]
Use `curl` like so

```bash
curl https://disroot.org/_matrix/client/r0/sync?access_token=<replace_with_your_token>
```
and see what room  contains the number above.

**Comment by albjeremias** [comment]
ok, more info from the discussion in the nheko room in matrix...

` $ cat matrix.log | grep -E "[0-9]{19,}"`
and i didn't figure this number... i think it is another request, not the one you are referring... 

> Well `/sync` with no since field.
> Ok, so perhaps it's not an issue in `/sync`, but another endpoint that nheko is hitting.

another relevant thing:
fractal-gtk-git works for me!

**Comment by albjeremias** [comment]
@mujx can this at least be open? so that some1 can try to help me? thanks.
