### ISSUE TITLE
Code signing Windows installer

### ISSUE THREAD

**Issue by pkoziol** [mujx/nheko#343]
You probably need to consider signing Windows installer if you do not want to scare users.

I wanted to test nheko (written in C++ and Qt - looks promising!), but unfortunately Windows 10 Smart Screen tried to protect me and blocked me from running it. I [checked it with VirusTotal](https://www.virustotal.com/#/file/c3bda8010ed4ee1c0f9e832f9ec548c33a5b8981da507dfa408551cd79b8ec05/detection) and it looks OK, Luckily there is option to bypass Smart Screen in two clicks, so it is not big problem, but we should not train users to ignore security warnings.

On the other hand I could not find way to get free certificate for open-source project. I only found that [yarn "recently" had similar problem](https://github.com/yarnpkg/yarn/issues/4403).

**Comment by xvitaly** [comment]
> On the other hand I could not find way to get free certificate for open-source project.

[Certum sells](https://www.certum.eu/en/cert_offer_code_signing/) 1 year certificates for code signing for 28 € (excl. VAT).

**Comment by mujx** [comment]
I'm closing this because there is no free of charge solution. Feel free to re-open if that's not the case.
