### ISSUE TITLE
Memory hungry build process

### ISSUE THREAD

**Issue by lbeltrame** [mujx/nheko#344]
### System:

- Nheko version: 0.43-8704265
- Installation method: Source
- Operating System: openSUSE Tumbleweed
- Qt version: 5.11
- C++ compiler: GCC 8
- Desktop Environment:KDE Plasma 5.13.80 (git master version)

### Actual behavior:

Building nheko can consume 1-2G per compiler process. Compiling on a quad core machine (8G RAM) with `-j 4` can easily exhaust the system memory.  I'm not sure this is is avoidable, but perhaps it should be pointed out in the README.

I didn't notice it at first as I initially built nheko on a 32G RAM machine.

**Comment by mujx** [comment]
Are you using `-GNinja` or Makefiles? You can always use one process but it would be slower. I don't know how clang compares.

**Comment by lbeltrame** [comment]
Currently I'm using `make` (mostly because I'm also using this a testbed for possible distro packaging). I could try with `ninja` and see if it fares better.

**Comment by mujx** [comment]
Ninja is actually more resource hungry. I don't know if we can do much about it, usually C++ & templates behave like this.

**Comment by lbeltrame** [comment]
It's not a huge issue, as long as it is known (IMO). Perhaps it should be mentioned in the README for those who build from source.

**Comment by mujx** [comment]
Closing this since there isn't a lot we can do about it.

Compiling with `make -j 1` keeps things under control with around 600-800MB.
