### ISSUE TITLE
Crash with UKNOWN_MESSAGE_INDEX when entering a preexisting room

### ISSUE THREAD

**Issue by lbeltrame** [mujx/nheko#345]
### System:

- Nheko version: 0.4.3-7ecabcd
- Installation method:  Source
- Operating System: openSUSE Tumbleweed
- Qt version: 5.11
- C++ compiler: GCC 8.1
- Desktop Environment: KDE Plasma 5.13.80

### Actual behavior

Entering a preexisting room causes an exception to be raised, followed by SIGABRT.
I have noticed this can (temporarily?) go away with a logout/login. I've noticed this happens when the program crashes and is restarted.
It will keep on crashing when joining the room that caused the issue until a logout/login is done.

The log displays many lines before the crash: these are all related to the devices present in the room.

```
[2018-06-18 23:44:28.885] [crypto] [info] Could not find inbound megolm session (XXXX)
```

Then, it crashes with:

```
terminate called after throwing an instance of 'mtx::crypto::olm_exception'
  what():  olm_group_decrypt: UNKNOWN_MESSAGE_INDEX
```

### Expected behavior

nheko should not crash.

### Steps to reproduce

Join a pre-existing room.

### Debugger backtrace 

http://paste.opensuse.org/71215869

**Comment by lbeltrame** [comment]
Interestingly, only one of my rooms in my homeserver triggers this exception. The others are completely unaffected.

**Comment by mujx** [comment]
From a quick look it seems like an un-handled exception from 

https://github.com/mujx/nheko/blob/7ecabcd61410783267f1ef4353d65716b84f7f83/src/timeline/TimelineView.cc#L316

**Comment by lbeltrame** [comment]
The room which triggers this exception is also the oldest on the homeserver (created 1-1.5 years ago): I have excluded the specific user (and their devices) being the culprit as they are also in other rooms which do not exhibit this behavior.
