### ISSUE TITLE
Build process downloads additional dependencies

### ISSUE THREAD

**Issue by lbeltrame** [mujx/nheko#346]
### System:

- Installation method: Source
- Operating System: openSUSE Tumbleweed
- Qt version: 5.11
- C++ compiler: GCC 8.1

### Problem

The build process downloads `lmdbxx` and `Tweeny` off git and it is unclear whether this step can be skipped. The reason is that in light of packaging / distro integration, the build hosts of most major distributions explicitly disallow network access (or dependency bundling). 
I've looked through the README, but there is no explicit mention of these dependencies. Ideally, these should be searched like all the others and there should be a build switch like the `-DUSE_BUNDLEDXXX=FALSE` to disable this step.

**Comment by mujx** [comment]
Yes this needs to be fixed. We'll need `Findlmdbxx.cmake` & `FindTweeny.cmake` respectively.
