### ISSUE TITLE
Login button is hard/impossible to read using a dark system theme

### ISSUE THREAD

**Issue by PureTryOut** [mujx/nheko#355]
### System:

- Nheko version: 0.4.3-2749afb
- Installation method: AppImage
- Operating System: Gentoo Linux
- Qt version: 5.9.4
- C++ compiler: The one used by Travis/Binhost I guess
- Desktop Environment: Plasma

### Actual behavior

![screenshot_20180623_110346](https://user-images.githubusercontent.com/1565836/41807895-fe644bfc-76d5-11e8-84e0-c9fad4cdd7ed.png)

### Expected behavior

The login button to be easily readable, even for colour-blind people

### Steps to reproduce

Set nheko to use the system theme, and make sure your system theme is dark (in my case Breeze Dark).

It might be good to add a way to change nheko's theme from the login screen as well.

**Comment by mujx** [comment]
Is this still an issue?

**Comment by PureTryOut** [comment]
Well, it still isn't great, but it's way better that's for sure! Good enough for me to close now.

**Comment by mujx** [comment]
Could you send a screenshot? I'm not sure what Qt palette color to use for that.
