### ISSUE TITLE
Everything looks to tiny on a HiDPI display

### ISSUE THREAD

**Issue by dessalines** [mujx/nheko#356]
Text, Icons, everything make this unusable on a hidpi display. It might be worth looking into how other qt programs solve this issue, others such as qbittorrent seem to automatically solve this issue with no adjustment necessary.

**Comment by mujx** [comment]
Duplicate of #335.

Luckily the fix is as easy as setting a Qt flag. It has been delayed a bit because It should be tested on all platforms (in case something else breaks).
