### ISSUE TITLE
Rendering wierdness while switching communities

### ISSUE THREAD

**Issue by Cadair** [mujx/nheko#380]
### System:

- Nheko version: 0.5.1-00f99d9
- Installation method: AUR nheko-git
- Operating System: Arch Linux
- Desktop Environment: Plasma / i3

### Actual behavior
![nheko_rendering](https://user-images.githubusercontent.com/1391051/42997337-3a7a7e8e-8c0e-11e8-92d4-91fa76ffb9b8.png)

### Expected behavior

not that

### Steps to reproduce

Switch into global view or a very large community.

**Comment by mujx** [comment]
Resolved by 35067088f9ca02861d08f86c28843316b012b6a2
