### ISSUE TITLE
Make hover triggered menu actions opt-in

### ISSUE THREAD

**Issue by thinslice** [mujx/nheko#398]
How the emoji button and the other menus behave annoys me.
The emoji button opens a menu on hovering. The other menus close when I move the mouse away.

I am not saying it doesn't have advantages, but most users will dislike it.

**Comment by qazip** [comment]
The emoji "menu" also closes when you movet he mouse away. Though I do agree that it opens a bit too fast. Perhaps one should need to hover it for a bit longer to have it opened?
