### ISSUE TITLE
Feature Request: Close modals with ESC (or other key)

### ISSUE THREAD

**Issue by ptman** [mujx/nheko#399]
I'd hope for better keyboard accessibility. All image views, profile popus and settings should preferably be closable with ESC.

**Comment by mujx** [comment]
@ptman All the modals can be closed with esc. The ones that don't respond to esc are the image viewer and the emoji picker.

If that's not the case then there is a bug somewhere. Could you clarify which modals have this issue? Also some info about your system would be helpful to debug this.

**Comment by ptman** [comment]
Interesting. Indeed ESC sometimes works. I'm running the flatpak on Linux. But sometimes esc doesn't close anything. Terrible info for reproducing, I know.

**Comment by ptman** [comment]
I just got nheko 0.5.3 from flathub. Running it, opening settings and pressing esc does not close the settings.

**Comment by ananace** [comment]
Installed 0.5.4 from flathub, also noticed this being broken, ESC doesn't seem to be able to close any modal.

**Comment by mujx** [comment]
@ptman @ananace Could you give some info about desktop environment?

**Comment by ptman** [comment]
X11/notion

**Comment by ananace** [comment]
X11 / Plasma 5.13.4

**Comment by mujx** [comment]
@ptman @ananace Could you check if this issue is resolved in the latest version?

**Comment by mujx** [comment]
All the modals now have an button to close them so this shouldn't be an issue.
