### ISSUE TITLE
Look up the actual address of a user's HS when logging in

### ISSUE THREAD

**Issue by jansol** [mujx/nheko#4]
Currently the domain part of the mxid is used verbatim. This breaks when the server's client API is at a different domain from the mxid or a port other than 443.

Implementing this looks relatively straightforward using QDnsLookup. I'll try to submit a PR for this in the next couple of days, unless someone beats me to it.

**Comment by jansol** [comment]
Apparently this solution is heavily frowned upon.

**Comment by ara4n** [comment]
Just to be clear: there isn't a 'right' solution currently.  We're trying to switch over to .well-known URIs for discovery (as per https://docs.google.com/document/d/1RHQ5DEA6_2IZ5m2UIysPf8CuYaup-NrincEbV4Ef3jE/edit) which would help somewhat here, but instead you're better off just using a heuristic like "take the domain of the MXID, and see if https://$domain/_matrix/client works" than doing an SRV lookup on the *federation* endpoint and trying to talk to that.  Sorry :(
