### ISSUE TITLE
Auto-complete by pressing tab

### ISSUE THREAD

**Issue by PureTryOut** [mujx/nheko#40]
An auto-complete feature for display names would be nice. Start typing the first few letters of a display name, press tab to "scroll" through a list of nicks (or possibly even rooms known to the user) that apply to those letters, then either continue typing or press return to "select" the nickname and fill it in the chatbox.

**Comment by PureTryOut** [comment]
@Ralith iirc you implemented part of your message editing box from NaChat to nheko right? Was (a basic version of) auto-complete one of it's features by any chance?

**Comment by Ralith** [comment]
No. The bulk of the work to be done there (if a nachat-style approach is taken) is to make nheko track the membership of the room in a Qt data model, which can then be used to both maintain the displayed member list, and to populate a standard Qt autocompletion popup.
