### ISSUE TITLE
nheko freezes from time to time

### ISSUE THREAD

**Issue by Latesil** [mujx/nheko#404]
### System:

- Nheko version: 0.5.3
- Installation method: from Fedora's repo.
- Operating System: Fedora Linux
- Desktop Environment: KDE Plasma, 5.13.3

### Actual behavior

Nheko freezes some times, and I can only close and reopen it again.

### Expected behavior

Not to freeze.

### Steps to reproduce

That bug can occur anytime hence it very hard to predict when it freeze.

### Logs
[nheko.log](https://github.com/mujx/nheko/files/2290654/nheko.log)

### Debugger backtrace
[backtrace-nheko2.log](https://github.com/mujx/nheko/files/2290642/backtrace-nheko2.log)
[backtrace-nheko3.log](https://github.com/mujx/nheko/files/2290643/backtrace-nheko3.log)

**Comment by mujx** [comment]
Could you specify any steps to reproduce the issue or lay out what you did to trigger that behavior?

**Comment by mujx** [comment]
@Latesil Does this keep happening on the latest nightly ?
