### ISSUE TITLE
Previous selection stays active when making a new selection

### ISSUE THREAD

**Issue by NotAFile** [mujx/nheko#409]
### System:

- Nheko version: 0.5.3
- Installation method: fractal
- Operating System: linux
- Desktop Environment: i3

### Actual behavior

When creating a new selection inside a different message, the previous message stays selected. However, this is purely visual.

### Expected behavior

When creating a new selection, the previous selection should disappear.

### Steps to reproduce

 1. Select text in one message
 2. Select text in another message

**Comment by xvitaly** [comment]
I can confirm this issue. nheko 0.5.3 on Fedora 28 with KDE Plasma 5. Qt 5.10.1.
