### ISSUE TITLE
Scaling before login not possible

### ISSUE THREAD

**Issue by theowen** [mujx/nheko#410]
Before logging in, there is no option to scale UI 2x, 1.5x, etc. which makes it difficult to use on screens with higher resolution.

**Comment by Mikaela** [comment]
I may be suffering this since changing DE.

* https://matrix.to/#/!BPvgRcBVHzyFSlYkrg:matrix.org/$153450400217661sBvbu:matrix.org

**Comment by Mikaela** [comment]
![screenshot from 2018-08-17 14-05-28](https://user-images.githubusercontent.com/831184/44298258-5bbc9c80-a2e8-11e8-8f05-863545617eec.png)

Vurpo commented:

> nheko should really be using the Qt flag that automatically sets the scaling of the app rather than scaling itself based on some setting

However I didn't get response to whether I should open an issue about this and I don't know if this is the same issue or if I should open a different one.

**Comment by mujx** [comment]
@theowen Is this still an issue on the latest version?

**Comment by mujx** [comment]
The app now respects the current dpi so this shouldn't be an issue any more.
