### ISSUE TITLE
Sidebar is not rendered for 4:3 monitor (1280x1024)

### ISSUE THREAD

**Issue by lzap** [mujx/nheko#412]
Hello,

it looks like for my regular (old, 4:3) flat screen in resolution 1280x1024 it does not render the room list on the left, it renders it for the whole screen and I need to return back.

I quickly searched the codebase but cannot find the correct place where I can modify this misbehavior. Looks like the QT stack considers this a vertical screen.

**Comment by mujx** [comment]
That's the sidebar so it seems fine to me. 

The UI is responsive so it will change based on the available width. If you click on one of the rooms you should be able to see the messages.

**Comment by lzap** [comment]
Yeah the problem is I want this to be as on the original screenshot in the README - on the left side. The monitor is landscape 4:3 so I'd expect this behavior from the app.
