### ISSUE TITLE
Mute channels

### ISSUE THREAD

**Issue by qazip** [mujx/nheko#415]
This is a feature request. I don't think there's already an issue for this.

I'd like to be able to mute specific channels. It's annoying to having to constantly close pop-ups.

**Comment by mujx** [comment]
Closing in favor of #317 . As a temporary workaround you could configure the notification settings from Riot.

**Comment by unclechu** [comment]
@qazip @mujx I'm using this my own script as a temporary workaround to set "mentions only" notifications mode to a room: https://gist.github.com/unclechu/a4df6148d88fac0969404c9827012be8
I'm personally couldn't use Riot for that on my laptop for my main account that have more than 150 rooms (not enough RAM to sync account in Riot).

*P.S. You can get access token from your __nheko__ config:*
```bash
cat ~/.config/nheko/nheko.conf | grep ^access_token= | sed 's/^access_token=//'
```

But you couldn't copy room id from **nheko** now, so you have to obtain it some other way, like opening another account in Riot and try to find this room or invite yourself from other account, **nheko**'s interface doesn't have any representation of that value. @mujx It would be grate to have it in the interface.
