### ISSUE TITLE
version numbers broken on macOS

### ISSUE THREAD

**Issue by core-code** [mujx/nheko#423]
i've downloaded Version '0.5.4'  and version 0.5.2 but when selecting it in the Finder and using 'Get Info' it always shows Version '0.5'

**Comment by mujx** [comment]
How did you install it? Do you have both versions installed?

You can check in the `/Applications` directory.

**Comment by mujx** [comment]
In the [bundle](https://github.com/mujx/nheko/blob/master/cmake/MacOSXBundleInfo.plist.in) there are two versions (long & short). So you're probably referring to short.

**Comment by core-code** [comment]
here are the Info.plist entries from the last 4 releases:

0.5.1
    <key>CFBundleShortVersionString</key>
    <string>0.5</string>
    <key>CFBundleVersion</key>
    <string></string>

0.5.2
    <key>CFBundleShortVersionString</key>
    <string>0.5</string>
    <key>CFBundleVersion</key>
    <string></string>

0.5.3
    <key>CFBundleShortVersionString</key>
    <string>0.5</string>
    <key>CFBundleVersion</key>
    <string></string>

0.5.4
    <key>CFBundleShortVersionString</key>
    <string>0.5</string>
    <key>CFBundleVersion</key>
    <string></string>


so we see two problems.
1.) the CFBundleShortVersionString isn't aligned with the real version. it should read 0.5.4 for the 0.5.4 release instead of 0.5
2.) the CFBundleVersion is just empty. if you don't have build-numbers it should be set to the same value as the CFBundleShortVersionString

**Comment by core-code** [comment]
awesome, thanks!

**Comment by core-code** [comment]
i can confirm that this bug is fixed in the released version 0.5.5

thanks again
