### ISSUE TITLE
how to migrate channels, content from riot to nheko ? -question 

### ISSUE THREAD

**Issue by shirishag75** [mujx/nheko#435]
While I'm currently using 0.4.2.1 and have asked the maintainer to get the new version uploaded to debian archive https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908101 which hopefully will be uploaded soonish rather than later . 

Is there a way or a tool or something to migrate all channels, content from riot-web to nheko . I have a mix of IRC channels (using the irc bridge), matrix channels and even couple of telegram channels ( if memory serves right, matrix also has a telegram bridge.)

It would be nice if there is a way to talk between the two and use either for conversations.

**Comment by shirishag75** [comment]
as shared, Debian does have the old version. My issue is/was how to start nheko. If I go to the login page I get the following -

![nheko-login-page](https://user-images.githubusercontent.com/727626/45260246-54784280-b3ff-11e8-8347-bcd3b72d2d95.png)

now I don't remember my riot logins, although in riot everything just works. 

I do see the following in ~/.config/Riot/ -

```
~/.config/Riot$ ls
 Cache     Cookies-journal   GPUCache   'Local Storage'   QuotaManager           window-state.json
 Cookies   databases         IndexedDB   Preferences      QuotaManager-journal
```

**Comment by mujx** [comment]
There is no way to do a migration, you'll have to enter your matrix credentials in order to login to nheko. If you have an email in Riot you could submit a request to change the password.

**Comment by shirishag75** [comment]
I don't see that option in nheko, i.e. forgot/change password. Maybe it's a feature in one of the newer releases.

**Comment by mujx** [comment]
There is no such option in nheko. I was talking about Riot. You can join the Riot room in #riot:matrix.org
for some more help on how to recover you account credentials. After you know the matrix id & your password you'll be able to use them to log in to nheko and have all your channels available.
