### ISSUE TITLE
Unable to login: Error while setting maximum protocol version.

### ISSUE THREAD

**Issue by MeanEYE** [mujx/nheko#436]
### System:

- Nheko version: 0.4.2-1
- Installation method: Debian repository
- Operating System: Debian Testing
- Desktop Environment: Gnome/Wayland

### Actual behavior

Once ID is entered message "Error while setting maximum protocol version" appears at the bottom of the window. Terminal displays the following:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
     7.246: [warning] - We got a connection error when networkLayerState is Unknown
    14.018: [warning] - We got a connection error when networkLayerState is Unknown
```

### Expected behavior

Start and login.

### Steps to reproduce

Starting both from command line and from menu results in same issue.

### Logs

Directory `~/.cache/nheko` doesn't exist.

**Comment by MeanEYE** [comment]
In addition to that, `NetworkManager-wait-online.service` seems to be failing right now, however network is fully operational and available.

**Comment by mujx** [comment]
This is a very old version which is not worth debugging. Please try the latest version or a nightly build and report back if the problem persists.

**Comment by MeanEYE** [comment]
Okay. This is what came with Debian Testing, thought it was more recent. Thanks!

**Comment by MeanEYE** [comment]
Just to confirm, on newer version this is not an issue.
