### ISSUE TITLE
Emoji picker closes immediately or when still focused

### ISSUE THREAD

**Issue by rnhmjoj** [mujx/nheko#439]
### System:

- Nheko version: 0.5.5
- Installation method: nixpkgs unstable package
- Operating System: NixOS
- Qt version: 5.11.1
- C++ compiler: GCC 7.3.0
- Desktop Environment: none, just a wm

### Actual behavior
The window closes as soon as leaving the button and, when I menage to focus it, it still closes
while scrolling.
See this [recording](https://ipfs.io/ipfs/QmdBKYzsx2UEah1GtAESJMFP9Ci37fn26vNzzJoPxLZLww)

### Expected behavior
It should stay open for a couple of secondsm at least, in order to have time to actually reach it
and not close while focused.

### Steps to reproduce
I'm not sure because if no one noticed so far it probably means it's caused by a combination of different factors in my desktop. I use NixOS, a tiling wm (bspwm) and unclutter (still happens when disabled though).

**Comment by mujx** [comment]
The link isn't loading, not sure if there is an issue with it or it's just me.

I have a suspicion that it's related to the window manager but I'll have to test some more. It works fine on GNOME or mac/windows for example.

**Comment by rnhmjoj** [comment]
I used ipfs because github doesn't let you upload a video. It should work now.

**Comment by mujx** [comment]
The emoji picker has been removed.

**Comment by topaDev** [comment]
Any plans to bring it back? 
I think for the time being, downgrading won't hurt me too much...
