### ISSUE TITLE
Emoji in emoji picker are cut off (Debian Stretch/i3wm)

### ISSUE THREAD

**Issue by jfrederickson** [mujx/nheko#44]
Couldn't find an open issue for this, so here you go:

![screenshot_2017-07-08_11-40-44](https://user-images.githubusercontent.com/1923178/27986832-98ba79fa-63d2-11e7-93d5-c4bc4b94b498.png)

**Comment by MTRNord** [comment]
Basicly they are just too big as no size is defined

**Comment by mujx** [comment]
The fonts are too big in the whole app. You can use this commit 82b48d926dd835aa3adb5fb3a8426532386df5c0 until this is sorted out.

**Comment by mujx** [comment]
@jfrederickson Please let me know if the current master fixes the issue.

**Comment by mujx** [comment]
Closing as this turned out to be a qt issue.
