### ISSUE TITLE
there doesn't seem to a dd-mm-yy seperator on any channels when the date changes. 

### ISSUE THREAD

**Issue by shirishag75** [mujx/nheko#440]
First of all I dunno if the time-stamp shown is the one calculated on my system or wherever the home-server is, guess it's homeserver as don't see anything in settings to indicate otherwise - 

![nheko-screenshot](https://user-images.githubusercontent.com/727626/45576576-5aee3a80-b895-11e8-91d6-9cbf096ad428.png)
 
I also didn't see any date-timestamp telling about the date change nor could I get figure out anything from hovering over the time-stamp, this is from today's conversations in one of the rooms. 

![no-data-time-timestamp-screenshot at 2018-09-15 03-14-49](https://user-images.githubusercontent.com/727626/45576674-cafcc080-b895-11e8-9125-a9b0cb2bb1c0.png)

Even hovering over the time-stamp doesn't tell you anything. This is on 0.4.2 release though, might have been improved on in one of the newer releases but don't see it on the changelog though :(

I did go over the changelog couple of times and more but maybe I missed it . 

I am looking for something similar which is in riot - 

![riot-web-date-timestamp-announcement](https://user-images.githubusercontent.com/727626/45576874-be2c9c80-b896-11e8-9d00-09c0a45f7911.png)

the above image is from riot-web. 

https://github.com/mujx/nheko/blob/master/CHANGELOG.md

**Comment by mujx** [comment]
The `v0.4.2` is very old and is not worth opening issues for it.

The date is now added when new messages appear.
