### ISSUE TITLE
Only the first message is sent in a room

### ISSUE THREAD

**Issue by lbeltrame** [mujx/nheko#444]
### System:

- Nheko version: 0.5.5 (f108b8b)
- Installation method:  RPM
- Operating System: openSUSE Tumbleweed
- Qt version: 5.11
- C++ compiler: GCC 8
- Desktop Environment: KDE Plasma (git master)

### Actual behavior

When sending multiple messages in a room, only the first one is sent. Others aren't (see attached screenshot). Logs report no exchange of information between the server and the client, so it is safe to assume that the messages never leave the client.

When setting up a client (Riot) to look at the same room, the messages don't arrive.

![screenshot_20180919_071428](https://user-images.githubusercontent.com/25192/45732239-a711e580-bbdb-11e8-8fef-b95b73a3f8d8.png)

In Riot (the first "test" is from another test):

![screenshot_20180919_071630](https://user-images.githubusercontent.com/25192/45732301-f9530680-bbdb-11e8-88ef-52b4bea5d3e7.png)

### Expected behavior

Multiple messages are sent.

### Steps to reproduce

1. Enter a room
2. Send one message
3. Send another
4. Check with another client (Riot) whether they have been sent or not

**Comment by mujx** [comment]
Could you send some logs? Also which was the working commit from which you upgraded to the current version?

**Comment by lbeltrame** [comment]
Last working commit was a9ddc3b3d32cd0bdce2d88648bf2bd83662c44e0 or, in any case, before 1f3535bc43ea5b20dcca95fea42dbc8212e77a6b. Unfortunately as said before, there are no logs reported with this behavior occurred. 

I've then cleaned my cache and so I can't reproduce this anymore on that system (others seem unaffected, but I'll test a third install I have somehwere else today).

**Comment by mujx** [comment]
The commit you mentioned (https://github.com/mujx/nheko/commit/a9ddc3b3d32cd0bdce2d88648bf2bd83662c44e0) required a cache reset because the format changed. The change was related to how the megolm session keys are stored. In your case you couldn't access your own key so you couldn't decrypt the message.

I'll close because that was the expected behavior without a cache reset.

**Comment by lbeltrame** [comment]
I could reproduce it in another system (invalid cache still present). Should I just wipe the cache?

**Comment by mujx** [comment]
With the same version change?

**Comment by lbeltrame** [comment]
Yes, same version change.
