### ISSUE TITLE
decrypt_exported_sessions: ciphertext too small

### ISSUE THREAD

**Issue by dessalines** [mujx/nheko#445]
When I try to import e2e room keys, and enter the password, I get the error: `decrypt_exported_sessions: ciphertext too small`

I've tried with two different longer export passwords from riot, neither worked. 

version: `0.6.0-a6925fe | Linux`

**Comment by mujx** [comment]
Importing/exporting from/to Riot doesn't work at the moment as stated in the changelog and in #358 . The feature is compatible with nheko only.

**Comment by mujx** [comment]
Closing in favor of #358 to track the progress of this feature.
