### ISSUE TITLE
Room members window - Load more button - text not visible

### ISSUE THREAD

**Issue by z3ntu** [mujx/nheko#446]
### System:

- Nheko version: 0.6.0
- Installation method: Arch
- Operating System: Arch
- Desktop Environment: Plasma

### Actual behavior

The content in the room members window is too wide (due to a very long username in the nheko channel) and as the "Load more" button is centered, it isn't visible when you are scrolled on the left.
![image](https://user-images.githubusercontent.com/3768500/45904991-114ea400-bdef-11e8-96d7-0670b5e48fd1.png)

### Expected behavior

The text should be readable

### Steps to reproduce

Open the room members list in the nheko room and scroll to the bottom

**Comment by z3ntu** [comment]
Also a solution :smile:

**Comment by mujx** [comment]
👍 The modal is also resizable so it could be adjusted to view all the contents.
