### ISSUE TITLE
nheko 0.6 wont start on Windows

### ISSUE THREAD

**Issue by tim77** [mujx/nheko#449]
### System:

- Nheko version: 0.6
- Installation method: official .exe file
- Operating System: Windows 10 (1803)

### Actual behavior
Wont launch. Error at startup. Cant find - cmark.dll.
![nheko error](https://user-images.githubusercontent.com/5614476/45965492-4813fc80-c031-11e8-9c37-dd37d83db9e9.PNG)

### Expected behavior
Working nheko.

### Steps to reproduce
Install and run.

**Comment by springbov** [comment]
I had experienced that issue as well. I just ran the nightly installer and nheko started without the startup error.

**Comment by mujx** [comment]
@springbov Thanks for confirming. This is issue is now fixed in the nightly and in the `0.6.0` release.
