### ISSUE TITLE
decrypt_exported_sessions: ciphertext too small

### ISSUE THREAD

**Issue by doronbehar** [mujx/nheko#453]
### System:

- Nheko version: 0.6.1-276728a | Linux
- Installation method: Arch Linux User Repository, different build flags though:
```
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_BUNDLED_SPDLOG=OFF \
    -DUSE_BUNDLED_BOOST=OFF
```
- Operating System: Arch Linux
- Qt version: 5, From official repositories
- C++ compiler: GCC from official repositories
- Desktop Environment: Awesome

### Actual behavior

While trying to import keys exported from the settings of the web app on https://riot.im/app/#/settings, I received this error message:

```
decrypt_exported_sessions: ciphertext too small
```

### Expected behavior

No error message appears and I'm able to view events encrypted with a different client after a successful import.

### Steps to reproduce

1. Export your keys to a file from the settings of the web app on https://riot.im/app/#/settings
2. Enter nheko's settings and import the file (with the same password of course).

### Logs

Not sure if relevant but here are the last 4 messages:

```
[2018-09-27 15:59:08.575] [crypto] [info] received 2 to_device messages
[2018-09-27 15:59:08.575] [crypto] [warning] handling key request event: {
  "content": {
    "action": "request",
    "body": {
      "algorithm": "....................",
      "room_id": "................................",
      "sender_key": "...........................................",
      "session_id": "..........................................."
    },
    "request_id": "m0000000000000.00",
    "requesting_device_id": ".........."
  },
  "sender": "@doronbehar:matrix.org",
  "type": "m.room_key_request"
}
[2018-09-27 15:59:08.575] [crypto] [info] ignoring key request m0000000000000.00 because we were not the sender: 
requested(...........................................) ours(...........................................)
[2018-09-27 15:59:08.575] [crypto] [warning] handling key request event: {
  "content": {
    "action": "request",
    "body": {
      "algorithm": "....................",
      "room_id": "..............................",
      "sender_key": "...........................................",
      "session_id": "..........................................."
    },
    "request_id": "m1538053138301.24",
    "requesting_device_id": "B
```

### Additional info

I've tried to perform the reverse action and import to the web app the keys exported from `nheko`. The text file exported by `nheko` was just 1 line long and the text file exported from the web app started and ended like this:

```
-----BEGIN MEGOLM SESSION DATA-----
....
-----END MEGOLM SESSION DATA-----
```

**Comment by mujx** [comment]
The current implementation isn't compatible with Riot (mentioned in the release notes)

Relevant issues: #445 #358
