### ISSUE TITLE
empty device name causes issues in e2ee chats

### ISSUE THREAD

**Issue by uhoreg** [mujx/nheko#458]
Forwarded from https://bugs.debian.org/910405.  I haven't verified the issue myself.

### System:

- Nheko version: 0.6.1
- Installation method: Debian package
- Operating System: Debian testing
- Qt version: 5.11.1
- C++ compiler: gcc 7.3
- Desktop Environment: unknown

### Actual behavior

The user says:

> If the device name is empty in the login process (which does not warn anything when the field is left as is), the nheko session will not show up in other clients (riot.im in my case). Messages sent to chat rooms with e2ee enabled either don't get encrypted for existing rooms, or get encrypted but appear as unknown in other clients for rooms created by the nheko session.

### Expected behavior

The user says:

> Since the device name is needed for the session to be recognised by other clients, I would expect it either -
>    a. be a required field in the login process.
>    b. has a default value to be used when not specified.

**Comment by mujx** [comment]
It does have a default, `Nheko on <platform>`. And even if it didn't this is only the name of the device and it doens't affect the e2ee rooms.

If you login in on a new device it's natural that you won't be able to decrypt old messages, because you don't have the keys.

**Comment by uhoreg** [comment]
The original submitter closed the original bug as unreproducible, so I'm closing this issue too.
