### ISSUE TITLE
Permanent offline chat history/log with extensive search and plaintext export

### ISSUE THREAD

**Issue by v-fox** [mujx/nheko#461]
The reason that I and my buddies are interested in Matrix at all is XMPP's inability to sync history between multi-login client instances (usually, simultaneous use of mobile and PC) and IRC's & SIP's lack of multi-login. However, even if Matrix does support that, it's useless without every client guaranteeing that all (or at least, between users/rooms marked as important ones) messages are kept permanently locally and can be easily found months or years after being sent regardless of the connection state. They also need to be accessible from config/log backups in case if we would abandon Matrix entirely, so if they are not recorded in plaintext then their format should be easily dump-able by generic tools or there should be an option to dump them as such from inside the client. Import/export of history that is not found on server between different clients would be a great bonus to all that.

As a decent examples of offline history representation you can use [LeechCraft](https://github.com/0xd34df00d/leechcraft) and [Vacuum-IM](https://github.com/Vacuum-IM/vacuum-im). Consider this request to supersede #434 and similar.

**Comment by mujx** [comment]
I would suggest you to setup your own server, so you'll have access to all the history and easy export.

Storing messages for months or years is out of the scope of this client. The implementation of #434 would be server side mostly.

**Comment by v-fox** [comment]
A server, seriously ? Then what's the difference with running something P2P like Tox if you have to rely on your own hardware ? Or a XMPP server, configured for quirks of some compatible client that could make history synchronization work ? Why bother with another protocol, and raw one at that ? IRC with HTML but more obtuse ?

This is ridiculous. But at least now I know what I'm going to link to Matrix evangelists that have been writing praises and lengthy justifications for its adoption on tech news sites… After all, Nheko is listed as most feature-complete client for Linux [on matrix.org](https://matrix.org/docs/projects/clients-matrix).
