### ISSUE TITLE
Missing tray icon in KDE

### ISSUE THREAD

**Issue by mujx** [mujx/nheko#50]

**Comment by rokups** [comment]
Was this reported to plasma developers? Judging from comments this works on other desktops, except for plasma, right? I would submit bug report, just double-checking to avoid duplicate bug reports.

Also a ugly workaround would be saving icon to file in `/tmp` and loading it from file. That works. Is such workaround desirable?

**Comment by mujx** [comment]
I'm doing some custom painting over the icon to draw the unread message count, so maybe there is something wrong with my implementation. Although it works fine on gnome and xfce.

> Also a ugly workaround would be saving icon to file in /tmp and loading it from file.

So currently the icon isn't even loaded?

**Comment by rokups** [comment]
Icon was not painted because `TrayIcon` requested a zero-size icon rect. See description of submitted PR ;)
