### ISSUE TITLE
Page scrolls to the bottom after loading history

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#55]
What happens:
* I join a channel with a few hundred unread messages
* I scroll up one page
* It seems like the next page gets loaded from the server
* When the page finished loading, the scrollbar is at the bottom again
* I need to scroll up 2 pages now to load the third history page
* And so on.

What I expected:
* That it does not scroll down after loading one page
* Even better, if all history got loaded by default (maybe with a changeable limit in the settings, with a default of one week or so)

**Comment by mujx** [comment]
This occurs when you're hitting the top with the scrollbar. A workaround for now, is to go slower and wait for the messages to load.
