### ISSUE TITLE
Does not support encrypted channels?

### ISSUE THREAD

**Issue by ChrisFernandez** [mujx/nheko#56]
Hello we have some encrypted channels.. and is not seem to be working.

**Comment by PureTryOut** [comment]
Nope. Aside from Riot, so far no clients support encrypted chats yet. It's planned, but it's low on the priority list for now.

**Comment by ChrisFernandez** [comment]
thanks for the fast reply. to bad because I am SO tired of using "electron" apps they suck the memory out of my computers lol

**Comment by jcgruenhage** [comment]
Also, duplicate of #13, so you might want to close this ^^

**Comment by ChrisFernandez** [comment]
sure
