### ISSUE TITLE
support ed25519-keys, aes-sha2-encryption, session id, and sender device information

### ISSUE THREAD

**Issue by 5chdn** [mujx/nheko#58]
:-)

    End-to-end encryption information

    Event information

    User ID | @user:matrix.org
    -- | --
    Curve25519 identity key | none
    Claimed Ed25519 fingerprint key | none
    Algorithm | unencrypted
    Session ID | none

    Sender device information

    unknown device

**Comment by krombel** [comment]
Duplicate of #13

**Comment by 5chdn** [comment]
ok, wasn't aware it's olm.
