### ISSUE TITLE
Messages attached to wrong user

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#63]
I've seen this a few times now, though it happens rarely.

in nheko:

UserA:
> hey check this out!
> UserA: wow that's cool
> some other message

3 messages show up as written by UserA, while in reality this is how it should have been displayed:

UserA:
> hey check this out!

UserB:
> UserA: wow that's cool
> some other message

I guess this is happens when messages get sent/received almost at the same time.

**Comment by mujx** [comment]
Are you on the latest master?

**Comment by ollieparanoid** [comment]
Sorry, I was on 29e21e2970c2786eb1f6910c9da99a3dbbf0a49d (which is 10 days old already). I will rebuild soon and open this issue again if the problem persists.

**Comment by mujx** [comment]
I'm reopening because the latest commits didn't include any actual code changes.

**Comment by ollieparanoid** [comment]
It just happened again. I thought this was related to two people sending messages at the same time, but this time it is not the case, so I'll write down how it happened.

* I've sent a message, did some more chatting
* Closed nheko
* Opened it later
* Loaded the backlog roughly until the last message I wrote by keeping "page up" pressed for a minute or so (to work around #55)
* Now there's this in the chat window:
```
user A:
> 03:01 some
> 03:05 random
> 03:06 text
> 04:01 etc
> 04:12 *my own message here, listed as message from user A!*
```

So it was 11 minutes after the other message, still it got attached to the other user. And it only got attached wrong when loading the backlog, not when I sent it initially.

**Comment by mujx** [comment]
That's probably an error on the logic that merges the old events. I will set up some unit testing to figure this out.
