### ISSUE TITLE
Multiline messages not displayed correctly

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#64]
When someone sends this in Riot (without the `>` sign):
```
> ```
> first line
> _second line
>  ```
```

... it gets displayed in one line in nheko:
```
> ```firstline_secondline```
```

**Comment by mujx** [comment]
Those messages have a custom html format generated by Riot but nheko doesn't parse it yet.

**Comment by Ralith** [comment]
There is no HTML involved in multi-line messages. The newlines are encoded directly in the JSON string; nheko is doing something that is causing them to be stripped or ignored.
