### ISSUE TITLE
Show user count in channel

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#65]
*Sorry if this is a duplicate, I couldn't find a ticket about this or about adding a list of people in the channel.*

For me it would be very informative knowing the *count of people* in the channel, even if I did not see the usernames.

**Comment by mujx** [comment]
Any suggestions on where to put that number within the current UI?

**Comment by ollieparanoid** [comment]
Maybe right next to the channel name on the top, there's a lot of free space compared to the next line, which may hold a long channel description.


```
nheko (12345 $usersicon)
Discussion about nheko, the desktop client for Matrix (github.com/mujx/nheko)
````

**Comment by mujx** [comment]
The user count is now available in the room settings menu.
