### ISSUE TITLE
Memory leak in TrayIcon class

### ISSUE THREAD

**Issue by rokups** [mujx/nheko#83]
I am talking about this line: https://github.com/mujx/nheko/blob/da6e7c11dc9e387d8cf0009f91c966a3788a98d9/src/TrayIcon.cc#L149

New icon engine is assigned but old one is not deleted. However deleting `icon_` before assigning new one results in a crash when room is switched. Following log is displayed:

    error: nheko :: Class 'TrayIcon' has a base class 'QSystemTrayIcon' which does not have a complete definition.
    error: nheko :: Class 'MsgCountComposedIcon' has a base class 'QIconEngine' which does not have a complete definition.

**Comment by mujx** [comment]
The `QIcon` class takes ownership of the [QIconEngine](http://doc.qt.io/qt-5/qicon.html#QIcon-5) pointer and it's responsible for deleting it. You can set up a destructor for `MsgCountComposedIcon` and see it in action. 

But this shouldn't be called every time the room changes.

**Comment by rokups** [comment]
Silly me. Sorry for the noise.
