### ISSUE TITLE
Leaving room freezes client

### ISSUE THREAD

**Issue by rokups** [mujx/nheko#87]
Attempt to leave any room freezes application. It looks like so:
![freeze](https://user-images.githubusercontent.com/19151258/31076036-19edc864-a781-11e7-9ca3-b65df5207be9.png)

And produces this spam in console:
```
    61.539: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 48158, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    61.539: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 48169, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    61.544: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 48310, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    61.575: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 48486, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    63.486: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 48673, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    71.549: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 48995, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.194: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49049, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.209: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49091, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.212: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49132, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.227: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49173, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.244: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49218, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.259: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49259, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.275: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49300, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.291: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49341, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.307: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49382, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.323: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49423, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.339: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49464, resource id: 88087392, major code: 130 (Unknown), minor code: 3
    72.356: [warning] - QXcbConnection: XCB error: 8 (BadMatch), sequence: 49505, resource id: 88087392, major code: 130 (Unknown), minor code: 3
```

Clicking logout button presents confirmation dialog properly and it all works.

OS: Archlinux
Desktop: KDE Plasma5

**Comment by Ralith** [comment]
Bringing up the room switcher produces similar results for me. The room switcher actually works fine, you just can't see it at all--only a rectangular cutout in the dimming.

**Comment by mujx** [comment]
Is this still an issue on KDE? Does it happen with any other modal? (e.g logout)

**Comment by rokups** [comment]
Still happens when leaving room. Logout modal works fine.

**Comment by Fryboyter** [comment]
Just tested the current Git version. Under Arch and Plasma (all updates are installed) I have the same problem as rokups. The error messages are also identical.

**Comment by mujx** [comment]
On my system only the Logout dialog works correctly. All the others have the same problematic behavior.

**Comment by Fryboyter** [comment]
The changes seem to have fixed the problem. Just entered and left several rooms without the client being frozen.

**Comment by mujx** [comment]
@Fryboyter How about the other dialogs? (join/create room, logout etc)

**Comment by rokups** [comment]
@mujx join/create room/leave room all have this issue. Logout dialog however works properly.

**Comment by rokups** [comment]
I am afraid things are worse now.

Now every dialog except one is invisible:
![1](https://user-images.githubusercontent.com/19151258/36340852-80dda1d8-13ed-11e8-90b0-67710488d1e6.png)

"Create room" dialog looks like this:
![2](https://user-images.githubusercontent.com/19151258/36340853-8208463a-13ed-11e8-927e-7cee7721ab3d.png)

**Comment by mujx** [comment]
I tested the fix on the following setup in Debian 9
1. Plasma version 5.8.6
2. KDE Frameworks 5.28.0
3. Qt version 5.7.1

**Comment by rokups** [comment]
Versions here:
* Plasma 5.12
* KDE Frameworks 5.43
* Qt 5.10.1

**Comment by mujx** [comment]
I actually I think this is an issue with qt 5.10.1. I got the exact problem regardless of linux or kde. Could you try with 5.10.0 or older?

**Comment by rokups** [comment]
You are right! Qt 5.10.0 works flawless

**Comment by mujx** [comment]
Closing as resolved because this is a qt bug. I will try to create a minimal example and file a bug report. @rokups Thanks for the help!
