### ISSUE TITLE
Formatting usernames

### ISSUE THREAD

**Issue by PureTryOut** [mujx/nheko#9]
Usernames right now look a bit... confusing...

![screenshot_2017-04-25_09-57-45](https://cloud.githubusercontent.com/assets/1565836/25374454/ca8aa28a-299d-11e7-8f38-2a7deea70367.png)
![screenshot_2017-04-25_09-58-32](https://cloud.githubusercontent.com/assets/1565836/25374463/d83db868-299d-11e7-8e94-5a5f4263c9b0.png)

The display name should be shown instead.

**Comment by mujx** [comment]
Yes, that's definitely a problem, especially with bots and bridge users

**Comment by mujx** [comment]
Implemented in f2ce910b16b2efc4aaead15e55d3739077c94c5b.
