### ISSUE TITLE
Better UX while offline

### ISSUE THREAD

**Issue by jcgruenhage** [mujx/nheko#93]
nheko should tell the user somehow when it can't reach the HS. Currently, it all looks fine, and especially important: there is no way of seeing whether a message actually arrived at the server or not. Red highlighting and a retry button would be great.

**Comment by jansol** [comment]
Also when coming back online nheko doesn't restart syncing automatically. One has to restart nheko in order to get new messages after reconnecting to the network.

**Comment by alphapapa** [comment]
Maybe this should be split into two bugs: one for displaying offline status to the user, and another for restoring the connection after it becomes available again (e.g. when I wake my system from sleep, I have to restart nheko or I never receive new messages).

**Comment by mujx** [comment]
The app will notify the user when it can't connect and it will keep retrying on failure, so I think we can close this.

Please re-open if necessary.
