### ISSUE TITLE
Backlog scrolls to wrong position after receiving a new message

### ISSUE THREAD

**Issue by ollieparanoid** [mujx/nheko#94]
I'm scrolling through a lot of backlog, and often the window jumps back up in the backlog, although I was quite a few pages further with reading. I think it happens whenever a new message arrives in the channel, but I am not sure. I have noticed this for a few days now. Currently running on 8390ff253d3688c3f76e3149d43d3120f9549359.

EDIT: I'm pretty sure now, that it happens, when I get a new message in the channel. The weird thing is, that it does not scroll all the way to the top, but a lot more up than where I was reading previously.

**Comment by ollieparanoid** [comment]
Detailed description:
* Enter a channel
* Scroll a few pages up to read backlog
* nheko saves this position
* Scroll to the bottom
* Scroll one page up
* When someone writes a message now, you will be sent back to the top where nheko saved the position

This does make reading long backlogs pretty hard. Could I help with fixing this somehow?

**Comment by mujx** [comment]
I can reproduce so I will take a look today. Thanks a lot for the detailed description.

**Comment by ollieparanoid** [comment]
Just tested and it's working. This really makes my life easier. Thank you so much! 🎉 🎉 👍

**Comment by mujx** [comment]
Happy to help!
