### ISSUE TITLE
Weird sidebar movement in some rooms

### ISSUE THREAD

**Issue by rokups** [mujx/nheko#95]
Sidebar appears to have multiple issues with handling movement.

* Some rooms work perfectly fine.
* Other rooms appear to work ok, but sidebar can not move as much to the right as in other rooms.
* Some rooms have sidebar "fixed", it can not be moved freely to the left or right. Splitter being locked into position causes sidebar width changes when switching between rooms where sidebar works and where it is locked.
* In rooms where sidebar is locked collapsing it to the left causes incorrect display of entire application window. Releasing splitter when sidebar is collapsed in this state leaves application in broken state and restart is required.

See video below:
[![](https://img.youtube.com/vi/VlLRQBAFM4Y/0.jpg)](https://www.youtube.com/watch?v=VlLRQBAFM4Y)

**Comment by mujx** [comment]
It happens on rooms where the topic can't fit in the available space and the widgets probably pushes the other items. 

Btw you can reset the broken state by resizing the window.

**Comment by rokups** [comment]
Is making topic widget multiline an acceptable solution? I got it working. Say "yes" and i make PR :)

![multiline-topic](https://user-images.githubusercontent.com/19151258/31770457-aa5a23a4-b4e0-11e7-861a-6c297335a806.png)

**Comment by mujx** [comment]
Thanks a lot for you work! The icons look fine but ideally I would prefer the topic to be one line with the text elided on the right. 

It would probably be easy to update the text in a `resizeEvent` handler.

**Comment by rokups** [comment]
It definitely looks better when topic is one line, but it presents usability problem - there is no easy way to view such very large topic. The only way is to horizontally resize application window until text fits. If topic is long enough there would not even be enough space on monitor to do it in one go without moving window to the left. Topic label could have a tooltip with a full topic, but it would be cumbersome and links would not be clickable.

**Comment by mujx** [comment]
Yes, I agree on this. There should be a way to click and view the whole topic eventually.

**Comment by rokups** [comment]
There seems to be no easy fix for eliding topic. Text wrap does some magic which makes label to not fight for width when resizing. I made elided label class that handles clickable links (although it is very ugly hack), but it is not very useful with that resizing-jumping issue at hand. Any ideas what i could try to make `QLabel` be conservative about it's size? Seems like i tried nearly all available size policy combinations..

**Comment by mujx** [comment]
I pushed https://github.com/mujx/nheko/commit/8299a74775bcdf917d58038fd35b2fdd208d4154 but the text doesn't cover all the available space because of the spacer.
